# ABOUTME: Field and type mappings for IMO GISIS data import.
# ABOUTME: Maps IMO GISIS CSV fields to internal schema and enum values.

"""
IMO GISIS Field Mappings

Contains all mapping dictionaries for converting IMO GISIS data to internal schema:
- Field name mappings (GISIS column names to internal field names)
- Casualty type mappings (IMO casualty types to IncidentType enum)
- Ship type mappings (IMO ship types to VesselType enum)
- Cause mappings (contributing factors to CauseCategory enum)
- Status mappings (investigation status to IncidentStatus enum)
"""

from typing import Dict

from worldenergydata.modules.marine_safety.constants import (
    CauseCategory,
    IncidentStatus,
    IncidentType,
    VesselType,
)

# IMO GISIS field name mappings to internal field names
FIELD_MAPPINGS: Dict[str, str] = {
    # Ship identification
    "IMO_NUMBER": "imo_number",
    "IMO NUMBER": "imo_number",
    "IMO NO": "imo_number",
    "IMO NO.": "imo_number",
    "IMONUMBER": "imo_number",
    "SHIP_NAME": "vessel_name",
    "SHIP NAME": "vessel_name",
    "VESSEL_NAME": "vessel_name",
    "VESSEL NAME": "vessel_name",
    "NAME_OF_SHIP": "vessel_name",
    "NAME OF SHIP": "vessel_name",
    # Ship details
    "FLAG_STATE": "flag_state",
    "FLAG STATE": "flag_state",
    "FLAG": "flag_state",
    "SHIP_TYPE": "vessel_type",
    "SHIP TYPE": "vessel_type",
    "TYPE_OF_SHIP": "vessel_type",
    "TYPE OF SHIP": "vessel_type",
    "VESSEL_TYPE": "vessel_type",
    "GROSS_TONNAGE": "gross_tonnage",
    "GROSS TONNAGE": "gross_tonnage",
    "GT": "gross_tonnage",
    "YEAR_OF_BUILD": "year_built",
    "YEAR OF BUILD": "year_built",
    "YEAR_BUILT": "year_built",
    "BUILT": "year_built",
    "CLASSIFICATION_SOCIETY": "classification_society",
    "CLASSIFICATION SOCIETY": "classification_society",
    "CLASS": "classification_society",
    # Incident date/time/location
    "DATE_OF_OCCURRENCE": "incident_date",
    "DATE OF OCCURRENCE": "incident_date",
    "OCCURRENCE_DATE": "incident_date",
    "INCIDENT_DATE": "incident_date",
    "EVENT_DATE": "incident_date",
    "DATE": "incident_date",
    "TIME_OF_OCCURRENCE": "incident_time",
    "TIME OF OCCURRENCE": "incident_time",
    "TIME": "incident_time",
    "LATITUDE": "latitude",
    "LAT": "latitude",
    "LONGITUDE": "longitude",
    "LON": "longitude",
    "LONG": "longitude",
    "POSITION": "position",
    "LOCATION": "location_description",
    "PLACE_OF_OCCURRENCE": "location_description",
    "PLACE OF OCCURRENCE": "location_description",
    "AREA": "area",
    "WATERS": "waters",
    # Casualty classification
    "NATURE_OF_CASUALTY": "incident_type",
    "NATURE OF CASUALTY": "incident_type",
    "CASUALTY_TYPE": "incident_type",
    "CASUALTY TYPE": "incident_type",
    "TYPE_OF_CASUALTY": "incident_type",
    "TYPE OF CASUALTY": "incident_type",
    "CATEGORY": "casualty_category",
    "CASUALTY_CATEGORY": "casualty_category",
    "CASUALTY CATEGORY": "casualty_category",
    "SEVERITY": "severity",
    "SEVERITY_CLASSIFICATION": "severity",
    # Summary and description
    "SUMMARY_OF_EVENTS": "description",
    "SUMMARY OF EVENTS": "description",
    "SUMMARY": "description",
    "NARRATIVE": "description",
    "DESCRIPTION": "description",
    "SYNOPSIS": "description",
    "BRIEF_DESCRIPTION": "description",
    # Casualties
    "FATALITIES": "fatalities",
    "DEATHS": "fatalities",
    "NUMBER_OF_DEATHS": "fatalities",
    "NUMBER OF DEATHS": "fatalities",
    "INJURIES": "injuries",
    "INJURED": "injuries",
    "NUMBER_OF_INJURIES": "injuries",
    "NUMBER OF INJURIES": "injuries",
    "MISSING_PERSONS": "missing_persons",
    "MISSING PERSONS": "missing_persons",
    "MISSING": "missing_persons",
    "NUMBER_MISSING": "missing_persons",
    # Environmental impact
    "POLLUTION_QUANTITY": "pollution_quantity",
    "POLLUTION QUANTITY": "pollution_quantity",
    "OIL_SPILL": "pollution_quantity",
    "OIL SPILL": "pollution_quantity",
    "POLLUTION_TYPE": "pollution_type",
    "POLLUTION TYPE": "pollution_type",
    "ENVIRONMENTAL_IMPACT": "environmental_impact",
    "ENVIRONMENTAL IMPACT": "environmental_impact",
    # Contributing factors and causes
    "CONTRIBUTING_FACTORS": "contributing_factors",
    "CONTRIBUTING FACTORS": "contributing_factors",
    "FACTORS": "contributing_factors",
    "PROBABLE_CAUSE": "probable_cause",
    "PROBABLE CAUSE": "probable_cause",
    "CAUSE": "probable_cause",
    "ROOT_CAUSE": "root_cause",
    "ROOT CAUSE": "root_cause",
    # Investigation details
    "INVESTIGATION_REPORT_URL": "report_url",
    "INVESTIGATION REPORT URL": "report_url",
    "REPORT_URL": "report_url",
    "REPORT URL": "report_url",
    "REPORT_LINK": "report_url",
    "INVESTIGATION_STATUS": "investigation_status",
    "INVESTIGATION STATUS": "investigation_status",
    "STATUS": "investigation_status",
    "INVESTIGATING_STATE": "investigating_state",
    "INVESTIGATING STATE": "investigating_state",
    "LEAD_INVESTIGATING_STATE": "investigating_state",
    # Reference numbers
    "GISIS_REFERENCE": "source_incident_id",
    "GISIS REFERENCE": "source_incident_id",
    "REFERENCE_NUMBER": "source_incident_id",
    "REFERENCE NUMBER": "source_incident_id",
    "REFERENCE": "source_incident_id",
    "MCI_REFERENCE": "source_incident_id",
    "CASUALTY_ID": "source_incident_id",
    "CASUALTY ID": "source_incident_id",
    "ID": "source_incident_id",
}

# IMO casualty type mappings to IncidentType enum values
CASUALTY_TYPE_MAPPINGS: Dict[str, str] = {
    # Collision categories
    "collision": IncidentType.COLLISION.value,
    "collision between ships": IncidentType.COLLISION.value,
    "collision with another ship": IncidentType.COLLISION.value,
    "contact": IncidentType.COLLISION.value,
    "contact with fixed object": IncidentType.COLLISION.value,
    "contact with floating object": IncidentType.COLLISION.value,
    "striking": IncidentType.COLLISION.value,
    "allision": IncidentType.COLLISION.value,
    # Grounding
    "grounding": IncidentType.GROUNDING.value,
    "stranding": IncidentType.GROUNDING.value,
    "grounding/stranding": IncidentType.GROUNDING.value,
    "ran aground": IncidentType.GROUNDING.value,
    # Fire and explosion
    "fire": IncidentType.FIRE.value,
    "fire on board": IncidentType.FIRE.value,
    "explosion": IncidentType.EXPLOSION.value,
    "fire/explosion": IncidentType.FIRE.value,
    "fire and explosion": IncidentType.FIRE.value,
    "fire and/or explosion": IncidentType.FIRE.value,
    # Flooding and structural
    "flooding": IncidentType.FLOODING.value,
    "hull failure": IncidentType.STRUCTURAL_FAILURE.value,
    "structural failure": IncidentType.STRUCTURAL_FAILURE.value,
    "foundering": IncidentType.FLOODING.value,
    "sinking": IncidentType.FLOODING.value,
    "loss of watertight integrity": IncidentType.FLOODING.value,
    "capsizing": IncidentType.CAPSIZING.value,
    "capsize": IncidentType.CAPSIZING.value,
    "listing": IncidentType.FLOODING.value,
    "loss of stability": IncidentType.CAPSIZING.value,
    # Equipment and machinery
    "equipment failure": IncidentType.EQUIPMENT_FAILURE.value,
    "machinery failure": IncidentType.EQUIPMENT_FAILURE.value,
    "machinery damage": IncidentType.EQUIPMENT_FAILURE.value,
    "loss of propulsion": IncidentType.LOSS_OF_PROPULSION.value,
    "propulsion failure": IncidentType.LOSS_OF_PROPULSION.value,
    "engine failure": IncidentType.LOSS_OF_PROPULSION.value,
    "loss of steering": IncidentType.LOSS_OF_CONTROL.value,
    "steering failure": IncidentType.LOSS_OF_CONTROL.value,
    "loss of control": IncidentType.LOSS_OF_CONTROL.value,
    "loss of electrical power": IncidentType.EQUIPMENT_FAILURE.value,
    "blackout": IncidentType.EQUIPMENT_FAILURE.value,
    # Personnel casualties
    "occupational accident": IncidentType.PERSONNEL_INJURY.value,
    "personnel injury": IncidentType.PERSONNEL_INJURY.value,
    "injury": IncidentType.PERSONNEL_INJURY.value,
    "man overboard": IncidentType.PERSONNEL_INJURY.value,
    "person overboard": IncidentType.PERSONNEL_INJURY.value,
    "fall overboard": IncidentType.PERSONNEL_INJURY.value,
    "fatality": IncidentType.FATALITY.value,
    "death": IncidentType.FATALITY.value,
    "loss of life": IncidentType.FATALITY.value,
    # Environmental
    "pollution": IncidentType.POLLUTION.value,
    "marine pollution": IncidentType.POLLUTION.value,
    "oil pollution": IncidentType.POLLUTION.value,
    "discharge": IncidentType.POLLUTION.value,
    "oil spill": IncidentType.POLLUTION.value,
    "chemical spill": IncidentType.POLLUTION.value,
    # Weather related
    "heavy weather damage": IncidentType.WEATHER_RELATED.value,
    "weather damage": IncidentType.WEATHER_RELATED.value,
    "parametric rolling": IncidentType.WEATHER_RELATED.value,
    "cargo shift": IncidentType.WEATHER_RELATED.value,
    # Near miss / hazardous
    "near miss": IncidentType.NEAR_MISS.value,
    "hazardous incident": IncidentType.NEAR_MISS.value,
    "marine incident": IncidentType.OTHER.value,
    "other": IncidentType.OTHER.value,
}

# IMO ship type mappings to VesselType enum values
SHIP_TYPE_MAPPINGS: Dict[str, str] = {
    # Tankers
    "oil tanker": VesselType.TANKER.value,
    "crude oil tanker": VesselType.TANKER.value,
    "product tanker": VesselType.TANKER.value,
    "chemical tanker": VesselType.TANKER.value,
    "chemical/oil products tanker": VesselType.TANKER.value,
    "lpg tanker": VesselType.TANKER.value,
    "lng tanker": VesselType.TANKER.value,
    "gas carrier": VesselType.TANKER.value,
    "tanker": VesselType.TANKER.value,
    # Cargo vessels
    "bulk carrier": VesselType.CARGO_VESSEL.value,
    "bulker": VesselType.CARGO_VESSEL.value,
    "general cargo": VesselType.CARGO_VESSEL.value,
    "general cargo ship": VesselType.CARGO_VESSEL.value,
    "cargo ship": VesselType.CARGO_VESSEL.value,
    "container ship": VesselType.CARGO_VESSEL.value,
    "containership": VesselType.CARGO_VESSEL.value,
    "container": VesselType.CARGO_VESSEL.value,
    "ro-ro cargo": VesselType.CARGO_VESSEL.value,
    "roro": VesselType.CARGO_VESSEL.value,
    "roll-on/roll-off": VesselType.CARGO_VESSEL.value,
    "reefer": VesselType.CARGO_VESSEL.value,
    "refrigerated cargo": VesselType.CARGO_VESSEL.value,
    "heavy lift": VesselType.CARGO_VESSEL.value,
    "barge": VesselType.CARGO_VESSEL.value,
    "deck cargo ship": VesselType.CARGO_VESSEL.value,
    # Offshore - drilling
    "drilling rig": VesselType.DRILLING_RIG.value,
    "drilling ship": VesselType.DRILLING_RIG.value,
    "drill ship": VesselType.DRILLING_RIG.value,
    "drillship": VesselType.DRILLING_RIG.value,
    "mobile offshore drilling unit": VesselType.MODU.value,
    "modu": VesselType.MODU.value,
    "semi-submersible": VesselType.SEMISUBMERSIBLE.value,
    "semisubmersible": VesselType.SEMISUBMERSIBLE.value,
    "semi-submersible drilling rig": VesselType.SEMISUBMERSIBLE.value,
    "jack-up": VesselType.JACKUP_RIG.value,
    "jackup": VesselType.JACKUP_RIG.value,
    "jack-up rig": VesselType.JACKUP_RIG.value,
    # Offshore - production
    "fpso": VesselType.FPSO.value,
    "floating production storage offloading": VesselType.FPSO.value,
    "fso": VesselType.FSO.value,
    "floating storage": VesselType.FSO.value,
    "flng": VesselType.FPSO.value,
    "production platform": VesselType.PRODUCTION_PLATFORM.value,
    "platform": VesselType.PRODUCTION_PLATFORM.value,
    "fixed platform": VesselType.PRODUCTION_PLATFORM.value,
    "tlp": VesselType.TLP.value,
    "tension leg platform": VesselType.TLP.value,
    "spar": VesselType.SPAR_PLATFORM.value,
    "spar platform": VesselType.SPAR_PLATFORM.value,
    # Support vessels
    "offshore supply vessel": VesselType.SUPPLY_VESSEL.value,
    "osv": VesselType.SUPPLY_VESSEL.value,
    "supply vessel": VesselType.SUPPLY_VESSEL.value,
    "platform supply vessel": VesselType.SUPPLY_VESSEL.value,
    "psv": VesselType.SUPPLY_VESSEL.value,
    "anchor handling tug supply": VesselType.ANCHOR_HANDLING.value,
    "ahts": VesselType.ANCHOR_HANDLING.value,
    "anchor handling": VesselType.ANCHOR_HANDLING.value,
    "anchor handler": VesselType.ANCHOR_HANDLING.value,
    "tug": VesselType.TUG.value,
    "tugboat": VesselType.TUG.value,
    "towboat": VesselType.TUG.value,
    "harbour tug": VesselType.TUG.value,
    "ocean tug": VesselType.TUG.value,
    "push tug": VesselType.TUG.value,
    "crew boat": VesselType.CREW_BOAT.value,
    "crewboat": VesselType.CREW_BOAT.value,
    "crew transfer vessel": VesselType.CREW_BOAT.value,
    "ctv": VesselType.CREW_BOAT.value,
    "standby vessel": VesselType.STANDBY_VESSEL.value,
    "standby safety vessel": VesselType.STANDBY_VESSEL.value,
    # Wind farm vessels
    "wind turbine installation vessel": VesselType.WIND_TURBINE_INSTALL.value,
    "wtiv": VesselType.WIND_TURBINE_INSTALL.value,
    "wind installation": VesselType.WIND_TURBINE_INSTALL.value,
    "cable layer": VesselType.CABLE_LAYER.value,
    "cable laying vessel": VesselType.CABLE_LAYER.value,
    "cable ship": VesselType.CABLE_LAYER.value,
    "service operation vessel": VesselType.SERVICE_VESSEL.value,
    "sov": VesselType.SERVICE_VESSEL.value,
    # Research and diving
    "research vessel": VesselType.RESEARCH_VESSEL.value,
    "research ship": VesselType.RESEARCH_VESSEL.value,
    "survey vessel": VesselType.RESEARCH_VESSEL.value,
    "diving support vessel": VesselType.DIVING_SUPPORT.value,
    "dsv": VesselType.DIVING_SUPPORT.value,
    "diving vessel": VesselType.DIVING_SUPPORT.value,
}

# Contributing factor mappings to CauseCategory enum
CAUSE_MAPPINGS: Dict[str, str] = {
    # Human error
    "human error": CauseCategory.HUMAN_ERROR.value,
    "human factor": CauseCategory.HUMAN_ERROR.value,
    "human element": CauseCategory.HUMAN_ERROR.value,
    "operator error": CauseCategory.HUMAN_ERROR.value,
    "navigation error": CauseCategory.HUMAN_ERROR.value,
    "watchkeeping": CauseCategory.HUMAN_ERROR.value,
    "fatigue": CauseCategory.HUMAN_ERROR.value,
    "situational awareness": CauseCategory.HUMAN_ERROR.value,
    "bridge resource management": CauseCategory.HUMAN_ERROR.value,
    # Equipment
    "equipment failure": CauseCategory.EQUIPMENT_FAILURE.value,
    "machinery failure": CauseCategory.EQUIPMENT_FAILURE.value,
    "mechanical failure": CauseCategory.EQUIPMENT_FAILURE.value,
    "technical failure": CauseCategory.EQUIPMENT_FAILURE.value,
    # Design
    "design deficiency": CauseCategory.DESIGN_FLAW.value,
    "design flaw": CauseCategory.DESIGN_FLAW.value,
    "structural design": CauseCategory.DESIGN_FLAW.value,
    "construction defect": CauseCategory.DESIGN_FLAW.value,
    # Maintenance
    "maintenance": CauseCategory.MAINTENANCE_ISSUE.value,
    "maintenance failure": CauseCategory.MAINTENANCE_ISSUE.value,
    "lack of maintenance": CauseCategory.MAINTENANCE_ISSUE.value,
    "poor maintenance": CauseCategory.MAINTENANCE_ISSUE.value,
    "inadequate maintenance": CauseCategory.MAINTENANCE_ISSUE.value,
    # Weather
    "weather": CauseCategory.WEATHER.value,
    "heavy weather": CauseCategory.WEATHER.value,
    "adverse weather": CauseCategory.WEATHER.value,
    "storm": CauseCategory.WEATHER.value,
    # Environmental
    "environmental": CauseCategory.ENVIRONMENTAL.value,
    "sea state": CauseCategory.ENVIRONMENTAL.value,
    "visibility": CauseCategory.ENVIRONMENTAL.value,
    "current": CauseCategory.ENVIRONMENTAL.value,
    "tide": CauseCategory.ENVIRONMENTAL.value,
    # Procedural
    "procedural": CauseCategory.PROCEDURAL.value,
    "procedure": CauseCategory.PROCEDURAL.value,
    "sms": CauseCategory.PROCEDURAL.value,
    "safety management": CauseCategory.PROCEDURAL.value,
    "non-compliance": CauseCategory.PROCEDURAL.value,
    # Training
    "training": CauseCategory.TRAINING.value,
    "inadequate training": CauseCategory.TRAINING.value,
    "lack of training": CauseCategory.TRAINING.value,
    "competence": CauseCategory.TRAINING.value,
    "certification": CauseCategory.TRAINING.value,
    # Communication
    "communication": CauseCategory.COMMUNICATION.value,
    "communication failure": CauseCategory.COMMUNICATION.value,
    "language barrier": CauseCategory.COMMUNICATION.value,
    "miscommunication": CauseCategory.COMMUNICATION.value,
    "vts": CauseCategory.COMMUNICATION.value,
    # Management
    "management": CauseCategory.MANAGEMENT.value,
    "shore management": CauseCategory.MANAGEMENT.value,
    "company policy": CauseCategory.MANAGEMENT.value,
    "commercial pressure": CauseCategory.MANAGEMENT.value,
    "manning": CauseCategory.MANAGEMENT.value,
    "crew fatigue": CauseCategory.MANAGEMENT.value,
    # External
    "external": CauseCategory.EXTERNAL.value,
    "third party": CauseCategory.EXTERNAL.value,
    "other vessel": CauseCategory.EXTERNAL.value,
    "shore side": CauseCategory.EXTERNAL.value,
}

# Investigation status mappings
STATUS_MAPPINGS: Dict[str, str] = {
    "completed": IncidentStatus.FINAL_REPORT.value,
    "complete": IncidentStatus.FINAL_REPORT.value,
    "final report published": IncidentStatus.FINAL_REPORT.value,
    "final report": IncidentStatus.FINAL_REPORT.value,
    "published": IncidentStatus.FINAL_REPORT.value,
    "preliminary report": IncidentStatus.PRELIMINARY_REPORT.value,
    "preliminary": IncidentStatus.PRELIMINARY_REPORT.value,
    "ongoing": IncidentStatus.UNDER_INVESTIGATION.value,
    "in progress": IncidentStatus.UNDER_INVESTIGATION.value,
    "under investigation": IncidentStatus.UNDER_INVESTIGATION.value,
    "investigating": IncidentStatus.UNDER_INVESTIGATION.value,
    "reported": IncidentStatus.REPORTED.value,
    "notified": IncidentStatus.REPORTED.value,
    "closed": IncidentStatus.CLOSED.value,
    "archived": IncidentStatus.ARCHIVED.value,
    "no investigation": IncidentStatus.CLOSED.value,
}
