@startmindmap

* Data Collected
** by API 
*** Well Data
*** Production Data
** by ZIP 
*** API Lookup
*** Approvals
*** Assignments
*** Bottomhole Pressure Survey
*** Borehole
*** Deepwater Natural Gas and Oil Qualified Fields
*** eWell Submissions
**** APD (Application for Permit to Drill)
**** APM (Applications for Production Management)
**** EOR (Enhanced Oil Recovery)
**** WAR (Work Authorization Request)
*** Facility/Measurement Points
*** Incidents of Non-Compliance
*** Lease Area Block
*** Lease Owner
*** Offshore Statistics by Water Depth
*** Oil Spill Financial Responsibility (OSFR)
*** Outer Continental Shelf Oil and Gas Production
*** Pipeline Locations
*** Pipeline Permits
*** Production by Planning Area
*** Production Data

@endmindmap
