# ABOUTME: E4 (#1027) — build cost_revision_trails.csv: dated sanction->revised->final cost statements per project.
# ABOUTME: Each trail point carries currency, kind, provenance tier, verbatim quote + URL. Trails compare WITHIN one currency.
"""
build_cost_revision_trails
==========================

Emits ``data/modules/cost/curated/cost_revision_trails.csv`` — the outturn
cost-trail table for #1027 (child of hardening epic #1023).

Why a separate table (not columns on ``sanctioned_projects``): a project's cost
is not one number but a *sequence* of dated statements — sanction estimate,
revision(s), spend-to-date, final outturn. Flattening that into one row loses
the shape (did it overrun? by how much? when was it re-baselined?), which is
exactly the "FID number vs. what it really cost" proof the presentation needs.

Rules held to (mirroring the sanctioned-projects intake discipline):

- Every point is attributable to the operator, a partner SEC/ASX/annual-report
  filing, or a regulator, with a verbatim quote — OR it is flagged
  ``provenance = trade_press`` and ``confidence = low`` so a trade-derived
  endpoint is never mistaken for a disclosed one.
- Currencies are NEVER converted. A trail lives in one currency; a project that
  reported NOK at PDO and USD later gets its points in their native currencies,
  and the reconciliation harness (E5) compares like-for-like.
- ``IN_SANCTIONED_SET`` = does this project have a row in sanctioned_projects.csv.
  False for trail-only projects (Pluto: AUD-native; Catcher: outturn-only) whose
  FID figure did not meet the USD/attribution import bar but whose *trail* is
  still a valid, sourced observation of cost evolution.

This is E4 v1. The Norwegian NOK regulator-tier trails (Johan Sverdrup Ph1,
Goliat, Aasta Hansteen — per-project investment revisions in NPD/Storting budget
documents) are a documented follow-up pass; see the E4 research record.
"""

from __future__ import annotations

import csv
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUT = (
    PROJECT_ROOT / "data" / "modules" / "cost" / "curated" / "cost_revision_trails.csv"
)
D = "2026-07-15"

FIELDS = [
    "PROJECT",
    "IN_SANCTIONED_SET",
    "STATEMENT_DATE",
    "VALUE_MM",
    "CURRENCY",
    "KIND",
    "BASIS",
    "PROVENANCE",
    "CONFIDENCE",
    "SOURCE_TITLE",
    "SOURCE_URL",
    "QUOTED_TEXT",
    "ACCESSED_DATE",
    "NOTES",
]

# KIND vocabulary: sanction_estimate | revised_estimate | spend_to_date |
#                  final_forecast | final_outturn
# PROVENANCE tiers: operator | partner_sec | partner_asx | regulator | trade_press


def t(
    project,
    in_set,
    date,
    value,
    ccy,
    kind,
    basis,
    prov,
    conf,
    title,
    url,
    quote,
    notes="",
):
    return {
        "PROJECT": project,
        "IN_SANCTIONED_SET": "True" if in_set else "False",
        "STATEMENT_DATE": date,
        "VALUE_MM": value,
        "CURRENCY": ccy,
        "KIND": kind,
        "BASIS": basis,
        "PROVENANCE": prov,
        "CONFIDENCE": conf,
        "SOURCE_TITLE": title,
        "SOURCE_URL": url,
        "QUOTED_TEXT": quote,
        "ACCESSED_DATE": D,
        "NOTES": notes,
    }


ROWS = [
    # ---- Sangomar Phase 1 (Woodside) — the exemplar trail, 4 dated operator/ASX points ----
    t(
        "Sangomar Phase 1",
        True,
        "2020-01",
        "4200",
        "USD",
        "sanction_estimate",
        "gross project cost at FID (Jan 2020), Phase 1",
        "operator",
        "high",
        "Oilfield Technology citing Reuters, 26 Mar 2020",
        "https://www.oilfieldtechnology.com/offshore-and-subsea/26032020/sangomar-project-partners-deliberating-timing/",
        "'US$4.2 billion Sangomar oil project'",
    ),
    t(
        "Sangomar Phase 1",
        True,
        "2021-04",
        "4600",
        "USD",
        "revised_estimate",
        "updated 100% project cost forecast after detailed engineering",
        "operator",
        "high",
        "Woodside Q1 2021 Report, 22 Apr 2021",
        "https://www.woodside.com/docs/default-source/investor-documents/quarterly-and-half-yearly-pdfs-and-data-tables/2021/q1-2021-report.pdf",
        "'The updated cost forecast is $4.6 billion (100% project) and reflects further detailed engineering of the project'",
    ),
    t(
        "Sangomar Phase 1",
        True,
        "2023-07",
        "5050",
        "USD",
        "revised_estimate",
        "cost estimate raised to a $4.9-5.2bn range (5050 = range midpoint recorded)",
        "operator",
        "high",
        "Woodside ASX 'Sangomar Project Update', 18 Jul 2023",
        "https://www.woodside.com/docs/default-source/asx-announcements/2023-asx/sangomar-project-update.pdf",
        "'The project cost estimate has increased to US$4.9-5.2 billion from the previous US$4.6 billion'",
        "Recorded as range midpoint 5050; range 4900-5200.",
    ),
    t(
        "Sangomar Phase 1",
        True,
        "2025-02",
        "5000",
        "USD",
        "final_outturn",
        "final Phase 1 cost, ~$5.0bn (lower end of the prior range)",
        "operator",
        "high",
        "Woodside ASX reserves statement + Sangomar update, 17 Feb 2025",
        "https://www.woodside.com/docs/default-source/asx-announcements/2025/woodside-releases-reserves-statement-and-sangomar-update.pdf",
        "'The final Sangomar Field Development Phase 1 cost was approximately $5.0 billion, at the lower end of the previously estimated range of $4.9 - $5.2 billion.'",
        "Trail: +19% sanction->final over 5 years; slipped first oil target.",
    ),
    # ---- Barossa (Santos) — 3 Santos-sourced points ----
    t(
        "Barossa",
        True,
        "2021-03",
        "3600",
        "USD",
        "sanction_estimate",
        "gross project cost at FID; EXCLUDES the separate Darwin LNG life-extension",
        "operator",
        "high",
        "Santos — Santos announces FID on the Barossa gas project",
        "https://www.santos.com/news/santos-announces-fid-on-the-barossa-gas-project-for-darwin-lng/",
        "'a final investment decision (FID) has been taken to proceed with the US$3.6 billion gas and condensate project'",
    ),
    t(
        "Barossa",
        True,
        "2024-01",
        "4550",
        "USD",
        "revised_estimate",
        "total capex now $4.5-4.6bn including Darwin Pipeline Duplication (4550 = midpoint)",
        "operator",
        "high",
        "Santos 2023 Fourth Quarter Report, 25 Jan 2024",
        "https://www.santos.com/wp-content/uploads/2024/01/2023-Fourth-Quarter-Report.pdf",
        "'Total capital expenditure is expected to be $4.5 to $4.6 billion for the project (including DPD).'",
        "Includes DPD scope not in the $3.6bn FID basis — a scope change, not pure overrun.",
    ),
    t(
        "Barossa",
        True,
        "2025-06",
        "3950",
        "USD",
        "spend_to_date",
        "JV spend to date at FPSO arrival in field",
        "operator",
        "high",
        "Santos — Barossa LNG FPSO arrives in field, 18 Jun 2025",
        "https://www.santos.com/news/barossa-lng-fpso-arrives-in-field-successfully-hooks-up-and-commences-final-commissioning-plans/",
        "'Santos and its joint venture partners, SK E&S and JERA Co., Inc. have invested US$3.95 billion (A$6.07 billion at today's rates)'",
    ),
    # ---- Kraken (EnQuest) — USD-reporting mid-cap, clean downward trail ----
    t(
        "Kraken",
        True,
        "2013-11",
        "3200",
        "USD",
        "sanction_estimate",
        "full-cycle gross capex at sanction (operator's own USD figure; sanction release itself was GBP-only)",
        "operator",
        "high",
        "EnQuest, restated in Kraken First Oil release, 26 Jun 2017",
        "https://www.enquest.com/media/press-releases/article/kraken-first-oil",
        "'The gross capital costs of the development are currently estimated to be approximately $2.5 billion, down from $3.2 billion'",
    ),
    t(
        "Kraken",
        True,
        "2017-06",
        "2500",
        "USD",
        "final_forecast",
        "gross capital costs at first oil, down 22% from sanction",
        "operator",
        "high",
        "EnQuest — Kraken First Oil, 26 Jun 2017",
        "https://www.enquest.com/media/press-releases/article/kraken-first-oil",
        "'currently estimated to be approximately $2.5 billion, down from $3.2 billion'",
        "EnQuest FY2017 results later trimmed further to ~$2.3bn (trail continues; that point trade-summarised, not added here).",
    ),
    # ---- Mad Dog Phase 2 (BP) — the canonical concept->sanction re-baseline ----
    t(
        "Mad Dog Phase 2 (Argos)",
        True,
        "2013",
        "22000",
        "USD",
        "revised_estimate",
        "original >$20bn concept estimate (recorded ~22000) before the redesign",
        "trade_press",
        "low",
        "Offshore Technology project profile (concept-era estimate)",
        "https://www.offshore-technology.com/projects/mad-dog-phase-2-gulf-of-mexico/",
        "'Initial development plans [had] spiralling costs that were estimated to be $22bn'",
        "Concept-era figure; trade-attributed. The revision itself is the point.",
    ),
    t(
        "Mad Dog Phase 2 (Argos)",
        True,
        "2016",
        "14000",
        "USD",
        "revised_estimate",
        "intermediate re-scoped estimate",
        "trade_press",
        "low",
        "Offshore Technology project profile",
        "https://www.offshore-technology.com/projects/mad-dog-phase-2-gulf-of-mexico/",
        "'Reduced the development cost to $14bn, which was further reduced to $9bn'",
    ),
    t(
        "Mad Dog Phase 2 (Argos)",
        True,
        "2016-12",
        "9000",
        "USD",
        "sanction_estimate",
        "gross (100%) cost at sanction — ~60% below the abandoned 2013 concept",
        "partner_sec",
        "high",
        "BHP Billiton Form 6-K half-year results, Feb 2017 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/0000811809/000119312517049179/d341376d6k.htm",
        "'now estimated to be US$9 billion on a 100 per cent basis (US$2.2 billion BHP Billiton share)'",
        "Exemplar of design-led cost reduction: 22->14->9 $bn. BP sanction 1 Dec 2016.",
    ),
    # ---- Gorgon (Chevron) — the classic megaproject overrun ----
    t(
        "Gorgon (incl. Jansz-Io)",
        True,
        "2009-09",
        "37000",
        "USD",
        "sanction_estimate",
        "first-phase total estimated project costs at FID (integrated LNG, incl. onshore)",
        "partner_sec",
        "high",
        "Chevron Corporation Form 10-K FY2011 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/93410/000095012312002976/f60351e10vk.htm",
        "'Total estimated project costs for the first phase of development are $37 billion.'",
    ),
    t(
        "Gorgon (incl. Jansz-Io)",
        True,
        "2016-03",
        "54000",
        "USD",
        "final_outturn",
        "cost at first LNG, ~$54bn (~46% over the FID estimate)",
        "trade_press",
        "low",
        "IndustryWeek — Chevron's $54 billion Gorgon LNG project starts production",
        "https://www.industryweek.com/operations/energy-management/article/21971352/chevrons-54-billion-gorgon-lng-project-starts-production",
        "'$54 billion Gorgon LNG project'",
        "Chevron announced a ~$15bn increase in Dec 2012 (AUD-denominated); the ~$54bn outturn is widely reported and Chevron-derived but flagged trade-tier here.",
    ),
    # ---- Wheatstone (Chevron) — sanction anchored, outturn unverified ----
    t(
        "Wheatstone (incl. Iago)",
        True,
        "2011-09",
        "29000",
        "USD",
        "sanction_estimate",
        "foundation-phase total estimated project costs at FID (integrated LNG)",
        "partner_sec",
        "high",
        "Chevron Corporation Form 10-K FY2011 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/93410/000095012312002976/f60351e10vk.htm",
        "'Total estimated project costs for the first phase of development are $29 billion.'",
        "Trade reports ~$34bn outturn but no Chevron-attributed figure located; outturn point deferred to a deeper pass.",
    ),
    # ---- Mariner (Equinor) ----
    t(
        "Mariner",
        True,
        "2012-12",
        "7000",
        "USD",
        "sanction_estimate",
        "gross project investments at FID, full development",
        "operator",
        "high",
        "Equinor press release, 21 Dec 2012",
        "https://www.equinor.com/news/archive/2012/12/21/21DecMariner",
        "'The project entails investments of more than USD 7 billion'",
    ),
    t(
        "Mariner",
        True,
        "2019",
        "7700",
        "USD",
        "final_outturn",
        "~$7.7bn reported at startup (first oil slipped 2017->Aug 2019)",
        "trade_press",
        "low",
        "Trade-press startup coverage (outturn ~$7.7bn)",
        "https://www.offshore-energy.biz/statoil-makes-fid-for-7-bln-mariner-development-uk/",
        "reported ~$7.7bn at startup",
        "Outturn trade-tier; an Equinor-attributed startup figure would upgrade this point.",
    ),
    # ---- Martin Linge (Total->Equinor) — dual-currency sanction, NOK outturn ----
    t(
        "Martin Linge (ex-Hild)",
        True,
        "2012-02",
        "4200",
        "USD",
        "sanction_estimate",
        "gross development investment at launch, operator-stated USD (= NOK 25.6bn)",
        "operator",
        "high",
        "TotalEnergies press release, 2 Feb 2012",
        "https://totalenergies.com/media/news/press-releases/total-launches-hild-field-development-north-sea-norway",
        "'This development will represent an investment of US$4.2 billion (NOK 25.6 billion)'",
        "Same statement gives NOK 25600 — see the NOK sanction row.",
    ),
    t(
        "Martin Linge (ex-Hild)",
        True,
        "2012-02",
        "25600",
        "NOK",
        "sanction_estimate",
        "gross development investment at launch, operator-stated NOK",
        "operator",
        "high",
        "TotalEnergies press release, 2 Feb 2012",
        "https://totalenergies.com/media/news/press-releases/total-launches-hild-field-development-north-sea-norway",
        "'US$4.2 billion (NOK 25.6 billion)'",
    ),
    t(
        "Martin Linge (ex-Hild)",
        True,
        "2021",
        "63000",
        "NOK",
        "final_outturn",
        "~NOK 63bn outturn after yard/hook-up problems and a ~5-year first-oil slip",
        "trade_press",
        "low",
        "NPD/Equinor reporting (outturn ~NOK 63bn)",
        "https://www.offshore-technology.com/projects/martin-linge-field-north-sea-norway/",
        "reported outturn ~NOK 63 billion",
        "~2.5x the NOK 25.6bn sanction. NPD budget-document verbatim would upgrade to regulator tier (deferred).",
    ),
    # ---- Peregrino Phase 2 (Equinor) — a RARE downward outturn ----
    t(
        "Peregrino Phase 2",
        True,
        "2015-02",
        "3500",
        "USD",
        "sanction_estimate",
        "gross investment at development-plan submission",
        "operator",
        "high",
        "Equinor press release, 27 Feb 2015",
        "https://www.equinor.com/news/archive/2015/02/27/27FebPeregrino",
        "'The project entails investments of approximately USD 3,5 billion.'",
    ),
    t(
        "Peregrino Phase 2",
        True,
        "2022-10",
        "3000",
        "USD",
        "final_outturn",
        "delivered within ~$3bn after a 2016 re-scope cut ~$500MM (downward outturn, rare)",
        "trade_press",
        "low",
        "NS Energy / startup coverage (delivered within $3bn estimate)",
        "https://www.marinetechnologynews.com/news/statoil-submits-peregrino-509758",
        "delivered within the $3 billion cost estimate",
        "Onstream 13 Oct 2022 (COVID delay from 2020). One of the few projects that came in BELOW sanction.",
    ),
    # ---- Frade (Chevron/Sojitz) ----
    t(
        "Frade (BC-4)",
        True,
        "2006-06",
        "2400",
        "USD",
        "sanction_estimate",
        "total planned gross investment at FID (partner Sojitz release)",
        "partner_sec",
        "high",
        "Sojitz Corporation FID release, 22 Jun 2006 (via Wayback)",
        "https://web.archive.org/web/2020/https://www.sojitz.com/en/news/2006/06/20060622-1.php",
        "'The total planned investment in the project is US$2.4 billion.'",
    ),
    t(
        "Frade (BC-4)",
        True,
        "2011",
        "3000",
        "USD",
        "spend_to_date",
        "~$3bn invested per project profile",
        "trade_press",
        "low",
        "Offshore Technology project profile",
        "https://www.offshore-technology.com/projects/fradefieldcamposbasi/",
        "'The partners invested approximately $3bn in developing the field.'",
    ),
    # ---- Jubilee Phase 1 (Tullow/Kosmos) ----
    t(
        "Jubilee Phase 1",
        True,
        "2009-07",
        "3150",
        "USD",
        "sanction_estimate",
        "original Phase 1 development budget",
        "operator",
        "medium",
        "Offshore Magazine — Jubilee brings Ghana into deepwater fold",
        "https://www.offshore-mag.com/production/article/16763668/jubilee-brings-ghana-into-deepwater-fold",
        "original budget US$3.15bn (Tullow-reported)",
    ),
    t(
        "Jubilee Phase 1",
        True,
        "2010-12",
        "3300",
        "USD",
        "final_forecast",
        "Phase 1 development cost stated at first oil by partner Kosmos",
        "operator",
        "high",
        "Kosmos Energy first-oil release (via Offshore Energy), Dec 2010",
        "https://www.offshore-energy.biz/kosmos-energy-celebrates-first-oil-from-3-3-billion-jubilee-field-development-offshore-ghana/",
        "'$3.3 billion world-class Jubilee Field development offshore the Republic of Ghana'",
        "Tullow AR later reported ~$3.35bn final — a rare near-on-budget megaproject.",
    ),
    # ---- TEN (Tullow) — came in UNDER sanction ----
    t(
        "TEN (Tweneboa-Enyenra-Ntomme)",
        True,
        "2013-05",
        "4000",
        "USD",
        "sanction_estimate",
        "gross capex to first oil approved at sanction",
        "operator",
        "high",
        "Offshore Magazine (Tullow executive quote)",
        "https://www.offshore-mag.com/deepwater/article/16754742/ten-extends-ghanas-tullows-deepwater-credentials",
        "'the $4-billion figure we approved at sanction'",
    ),
    t(
        "TEN (Tweneboa-Enyenra-Ntomme)",
        True,
        "2016-08",
        "4000",
        "USD",
        "final_forecast",
        "capital costs to first oil came in UNDER the $4bn sanction figure",
        "operator",
        "high",
        "Offshore Magazine (Tullow executive quote)",
        "https://www.offshore-mag.com/deepwater/article/16754742/ten-extends-ghanas-tullows-deepwater-credentials",
        "'our capital costs to first oil will come in under the $4-billion figure we approved at sanction'",
        "First oil Aug 2016, 39 months after sanction, within budget.",
    ),
    # ---- Culzean (Maersk/Total) ----
    t(
        "Culzean",
        True,
        "2015-08",
        "4500",
        "USD",
        "sanction_estimate",
        "operator's own parenthetical USD at sanction (= ~GBP 3bn)",
        "operator",
        "medium",
        "Maersk Oil announcement (Offshore Energy reprint)",
        "https://www.offshore-energy.biz/uk-approves-maersk-oils-culzean-field-development/",
        "'investing around GBP 3bn (USD 4.5 bn)'",
    ),
    t(
        "Culzean",
        True,
        "2016-12",
        "4000",
        "USD",
        "revised_estimate",
        "estimate cut ~$500MM to ~$4bn",
        "trade_press",
        "low",
        "Trade-press cost-cut coverage (Offshore Energy / Offshore Magazine, Dec 2016)",
        "https://www.offshore-energy.biz/uk-approves-maersk-oils-culzean-field-development/",
        "estimate cut by ~$500 million to ~$4 billion",
        "First gas Jun 2019 on schedule. Operator-verbatim Dec-2016 figure would upgrade this point.",
    ),
    # ---- Tyra Redevelopment (Maersk/Total) ----
    t(
        "Tyra Redevelopment",
        True,
        "2017",
        "3400",
        "USD",
        "sanction_estimate",
        "approved DUC investment, operator-parent-stated USD (= DKK 21bn)",
        "operator",
        "high",
        "A.P. Moller - Maersk Annual Report 2017",
        "https://investor.maersk.com/system/files-encrypted/nasdaq_kms/assets/2018/04/25/13-00-21/A.P._Moller_-_Maersk_Annual_Report_2017.pdf",
        "'approved an investment of approx. DKK 21bn (equal to approx. USD 3.4bn) in the full redevelopment of the Tyra gas field'",
    ),
    t(
        "Tyra Redevelopment",
        True,
        "2017",
        "21000",
        "DKK",
        "sanction_estimate",
        "approved DUC investment, DKK",
        "operator",
        "high",
        "A.P. Moller - Maersk Annual Report 2017",
        "https://investor.maersk.com/system/files-encrypted/nasdaq_kms/assets/2018/04/25/13-00-21/A.P._Moller_-_Maersk_Annual_Report_2017.pdf",
        "'approx. DKK 21bn (equal to approx. USD 3.4bn)'",
    ),
    t(
        "Tyra Redevelopment",
        True,
        "2024",
        "27000",
        "DKK",
        "final_outturn",
        "~DKK 27bn outturn after a ~2-year slip (guided 2022, first gas Mar 2024)",
        "trade_press",
        "low",
        "Trade-press outturn coverage (~DKK 27bn)",
        "https://investor.maersk.com/",
        "reported outturn ~DKK 27 billion",
        "Trade-tier; Danish Energy Agency / Total attribution would upgrade this point (deferred).",
    ),
    # ---- Mozambique LNG (TotalEnergies) — open trail ----
    t(
        "Mozambique LNG (Area 1)",
        True,
        "2020-07",
        "20000",
        "USD",
        "sanction_estimate",
        "total post-FID investment (integrated LNG, incl. onshore)",
        "operator",
        "high",
        "TotalEnergies news, 17 Jul 2020",
        "https://totalenergies.com/media/news/news/total-announces-signing-mozambique-lng-project-financing",
        "'Mozambique LNG represents a total post-FID investment of 20 B$.'",
        "OPEN trail: force majeure 2021-2024; restart-era cost-pressure statements (2024-2026) to be captured in a follow-up pass.",
    ),
    # ---- Pluto foundation (Woodside) — trail-only, AUD-native (not in sanctioned set) ----
    t(
        "Pluto LNG foundation",
        False,
        "2007-07",
        "11200",
        "AUD",
        "sanction_estimate",
        "original 100% project estimate at FID (integrated LNG)",
        "operator",
        "medium",
        "Offshore Technology project profile (Woodside FID estimate)",
        "https://www.offshore-technology.com/projects/pluto/",
        "A$11.2 billion original estimate (2007 FID)",
        "Trail-only: AUD-native, so it did not meet the sanctioned_projects USD-attribution bar.",
    ),
    t(
        "Pluto LNG foundation",
        False,
        "2011-06",
        "14900",
        "AUD",
        "revised_estimate",
        "revised 100% project estimate (+A$0.9bn to A$14.9bn)",
        "operator",
        "high",
        "Woodside announcement (via Offshore Energy), Jun 2011",
        "https://www.offshore-energy.biz/australia-woodside-ups-pluto-cost-estimate-to-usd-15-8-billion/",
        "'The revised estimate is expected to result in a A$900 million increase in cost to a total of A$14.9 billion (100% project).'",
        "+33% over the A$11.2bn FID estimate. First cargo Apr 2012.",
    ),
    # ---- Catcher (Premier Oil) — trail-only, outturn-forecast (not in sanctioned set) ----
    t(
        "Catcher Area",
        False,
        "2017-12",
        "1600",
        "USD",
        "final_forecast",
        "total forecast capex at first oil, stated as 30% below the sanctioned estimate",
        "operator",
        "high",
        "Premier Oil Full Year Results 2017 (RNS mirror)",
        "http://ajphku.com/pdf/2017-full-year-results7422.pdf",
        "'Total forecast capex for the Catcher Area remains at US$1.6 billion, 30 per cent lower than the sanctioned estimate.'",
        "Trail-only: the sanctioned USD estimate (~$2.3bn implied by the -30%) was never stated verbatim, so Catcher is not in sanctioned_projects. Another sub-sanction outturn.",
    ),
]


def main() -> int:
    with open(OUT, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(ROWS)
    projects = sorted({r["PROJECT"] for r in ROWS})
    print(f"wrote {len(ROWS)} trail points across {len(projects)} projects -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
