# ABOUTME: E2 (#1025) — normalize the #1020 tranche-1 award research into two curated CSVs.
# ABOUTME: contract_awards.csv (awards by asset class, bands as low/high ranges) + project_cost_statements.csv (partner nets).
"""
build_award_registry
====================

Emits two curated tables from the committed #1020 tranche-1 research record
(``docs/modules/cost/research/2026-07-14-contract-award-asset-registry-tranche1.md``):

* ``contract_awards.csv`` — one row per public contract award, classified by
  asset class (production_hub / sps / surf / installation / drilling_rig / other).
* ``project_cost_statements.csv`` — operator/partner project-level cost figures
  (gross capex, partner net share, carry mechanics) from press + SEC/ASX filings.

Two design rules carried from the sanctioned-projects discipline:

1. **A band is a sourced RANGE, never a point.** Contractors disclose award size
   in named tiers (TechnipFMC "large", Subsea7 "major", ...). We record
   ``VALUE_LOW_MM``/``VALUE_HIGH_MM`` from the contractor's *published band
   definition* and keep the band word — never a fabricated midpoint dressed as
   a figure. ``VALUE_BASIS`` says which kind of value it is.

2. **VALUE-NOT-PUBLIC is a row, not a deletion.** Frame-agreement awards (most
   US GoM SPS/SURF, all rig-fleet contracts) never disclose a value; recording
   the award with ``VALUE_BASIS = not_public`` preserves *what was awarded and to
   whom* — the scope — even when the price is hidden. That is itself a finding
   (see the #1020 record: GoM operators procure under undisclosed frame deals).

VALUE_BASIS vocabulary:
  point           — a single disclosed value (LOW == HIGH)
  band            — a contractor size tier (LOW..HIGH from the published definition)
  combined        — value bundles >1 project/scope; only an upper bound is knowable
  backlog         — rig contract backlog value (not directly a project-capex line)
  lease_contract  — FPSO lease+operate value spanning opex; NOT comparable to capex
  midstream       — third-party-owned export infra, OUTSIDE the operator's project capex
  not_public      — no value disclosed
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CURATED = ROOT / "data" / "modules" / "cost" / "curated"
D = "2026-07-15"

AWARD_FIELDS = [
    "PROJECT",
    "AWARD_YEAR",
    "CONTRACTOR",
    "ASSET_CLASS",
    "SCOPE_DESC",
    "VALUE_LOW_MM",
    "VALUE_HIGH_MM",
    "VALUE_BASIS",
    "BAND_WORD",
    "PROVENANCE",
    "SOURCE_TITLE",
    "SOURCE_URL",
    "ACCESSED_DATE",
    "NOTES",
]
STMT_FIELDS = [
    "PROJECT",
    "STATEMENT_YEAR",
    "COMPANY",
    "ROLE",
    "INTEREST_PCT",
    "FIGURE_TYPE",
    "VALUE_MM",
    "CURRENCY",
    "PROVENANCE",
    "SOURCE_TITLE",
    "SOURCE_URL",
    "QUOTED_TEXT",
    "ACCESSED_DATE",
    "NOTES",
]

# Published contractor band definitions (USD MM unless noted). "major" tiers are
# open-topped: HIGH left blank, threshold in LOW.
# TechnipFMC: significant 75-250, substantial 250-500, large 500-1000, major 1000+
# Subsea7:    sizeable 50-150, large 300-500, very large 500-750, major 750+
# Technip Energies: major 1000+ (EUR)


def A(
    project,
    year,
    contractor,
    asset,
    scope,
    low,
    high,
    basis,
    band,
    prov,
    title,
    url,
    notes="",
):
    return dict(
        zip(
            AWARD_FIELDS,
            [
                project,
                year,
                contractor,
                asset,
                scope,
                low,
                high,
                basis,
                band,
                prov,
                title,
                url,
                D,
                notes,
            ],
        )
    )


def S(
    project,
    year,
    company,
    role,
    interest,
    ftype,
    value,
    ccy,
    prov,
    title,
    url,
    quote,
    notes="",
):
    return dict(
        zip(
            STMT_FIELDS,
            [
                project,
                year,
                company,
                role,
                interest,
                ftype,
                value,
                ccy,
                prov,
                title,
                url,
                quote,
                D,
                notes,
            ],
        )
    )


AWARDS = [
    # ===== Guyana — Stabroek (ExxonMobil op) =====
    A(
        "Liza Phase 1",
        "2017",
        "SBM Offshore",
        "production_hub",
        "Liza Destiny FPSO — construct, install, lease & operate up to 10 yr",
        "",
        "",
        "not_public",
        "",
        "operator",
        "SBM Offshore / Offshore Energy",
        "https://www.offshore-energy.biz/sbm-confirms-fpso-contract-award-for-liza-project/",
        "Award-day lease value never disclosed; ~$1.2bn lease capitalization appears in the FID cost (see statements).",
    ),
    A(
        "Liza Phase 1",
        "2024",
        "SBM Offshore",
        "production_hub",
        "ExxonMobil purchase of FPSO Liza Destiny (ahead of max lease term)",
        "535",
        "535",
        "point",
        "",
        "operator",
        "SBM Offshore / OE Digital",
        "https://www.oedigital.com/news/520511-exxonmobil-concludes-535m-liza-destiny-fpso-buy-from-sbm-offshore",
        "Hard production_hub anchor: $535MM buyout.",
    ),
    A(
        "Liza Phase 1",
        "2017",
        "TechnipFMC",
        "sps",
        "17 enhanced vertical deepwater trees + 5 manifolds + controls",
        "",
        "",
        "not_public",
        "",
        "operator",
        "TechnipFMC",
        "https://www.technipfmc.com/en/investors/financial-news-releases/press-release/technipfmc-awarded-subsea-contract-for-exxonmobil-liza-in-guyana/",
        "Award predates TechnipFMC's banded-disclosure practice.",
    ),
    A(
        "Liza Phase 1",
        "2017",
        "Saipem",
        "surf",
        "EPCI risers/flowlines/structures + T&I of umbilicals/manifolds (66 km as-built)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Saipem",
        "https://www.saipem.com/en/media/press-releases/2017-05-10/saipem-new-epci-contract-awarded-exxonmobil-development-offshore",
    ),
    A(
        "Liza Phase 1",
        "2017",
        "Noble Corporation",
        "drilling_rig",
        "Noble Bob Douglas — 3-yr development drilling from 2018",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Offshore Magazine",
        "http://www.offshore-mag.com/articles/2017/08/noble-drillship-to-work-for-exxonmobil-offshore-guyana.html",
    ),
    A(
        "Liza Phase 2",
        "2019",
        "SBM Offshore",
        "production_hub",
        "Liza Unity FPSO (first Fast4Ward) — construct, install, lease; $1.14bn project financing",
        "",
        "",
        "not_public",
        "",
        "operator",
        "SBM Offshore",
        "https://www.sbmoffshore.com/newsroom/press-releases/2019/10-05-2019/sbm-offshore-awarded-contracts-exxonmobil-fpso-liza-unity",
    ),
    A(
        "Liza Phase 2",
        "2023",
        "SBM Offshore",
        "production_hub",
        "ExxonMobil purchase of FPSO Liza Unity (Nov 2023)",
        "1260",
        "1260",
        "point",
        "",
        "operator",
        "SBM Offshore",
        "https://www.sbmoffshore.com/newsroom/fpso-liza-unity-purchase-exxonmobil-completed/",
    ),
    A(
        "Liza Phase 2",
        "2018",
        "TechnipFMC",
        "sps",
        "30 EVDT trees + 8 manifolds + controls",
        "",
        "",
        "not_public",
        "",
        "operator",
        "TechnipFMC / Business Wire",
        "https://www.businesswire.com/news/home/20181022005773/en/TechnipFMC-Awarded-Subsea-Contract-ExxonMobil-Liza-Phase",
    ),
    A(
        "Liza Phase 2",
        "2018",
        "Saipem",
        "surf",
        "SURF EPCI (flowlines, risers, umbilical install)",
        "700",
        "700",
        "point",
        "",
        "operator",
        "Saipem",
        "https://www.saipem.com/en/media/press-releases/2018-08-21/saipem-awarded-surf-contracts-liza-phase-2-development-exxonmobil",
        "'The overall value of the Saipem contracts for Liza Phase 2 is approximately 700 million USD'",
    ),
    A(
        "Liza Phase 2",
        "2020",
        "Noble Corporation",
        "drilling_rig",
        "Drilling services agreement, 4 drillships, market-based dayrates reset 2x/yr; pooled campaign",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Noble / PR Newswire",
        "https://www.prnewswire.com/news-releases/noble-corporation-plc-announces-drilling-services-agreement-with-exxonmobil-in-the-guyana-suriname-basin-301003226.html",
        "Campaign pooled across Liza2/Payara/Yellowtail — not project-attributable.",
    ),
    A(
        "Payara",
        "2020",
        "SBM Offshore",
        "production_hub",
        "Prosperity FPSO — construct, install, lease; ~$0.98bn financing",
        "",
        "",
        "not_public",
        "",
        "operator",
        "SBM Offshore",
        "https://www.sbmoffshore.com/newsroom/sbm-offshore-awarded-contracts-exxonmobil-fpso-prosperity/",
    ),
    A(
        "Payara",
        "2024",
        "SBM Offshore",
        "production_hub",
        "ExxonMobil purchase of FPSO Prosperity (Nov 2024)",
        "1230",
        "1230",
        "point",
        "",
        "operator",
        "SBM Offshore / World Oil",
        "https://worldoil.com/news/2024/11/7/exxonmobil-guyana-sbm-offshore-complete-purchase-of-fpso-prosperity/",
    ),
    A(
        "Payara",
        "2020",
        "TechnipFMC",
        "sps",
        "41 EVDT trees + 10 manifolds + 6 flexible risers + controls",
        "500",
        "1000",
        "band",
        "large",
        "operator",
        "TechnipFMC / OE Digital",
        "https://www.oedigital.com/news/482115-technipfmc-nets-large-subsea-order-from-exxon-for-payara-development-in-guyana",
        "TechnipFMC 'large' = $500m-$1bn (publisher-verified).",
    ),
    A(
        "Payara",
        "2019",
        "Saipem",
        "surf",
        "EPCI ~130 km flowlines/risers/manifolds/flex/umbilicals",
        "",
        "880",
        "combined",
        "",
        "operator",
        "Saipem",
        "https://www.saipem.com/en/media/press-releases/2019-11-14/saipem-new-subsea-contract-guyana-and-variation-orders-ongoing",
        "~$880MM COMBINED with variation orders on other projects; Payara-only split not published — upper bound only.",
    ),
    A(
        "Payara",
        "2020",
        "Halliburton",
        "other",
        "Drilling & completions services",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/news/exxonmobil-technipfmc-halliburton-payara/",
    ),
    A(
        "Payara",
        "2022",
        "Noble Corporation",
        "drilling_rig",
        "CEA — 4 drillships pooled; dayrates low-to-high $400k/day, biannual reset",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Noble 8-K / Kaieteur News",
        "https://kaieteurnewsonline.com/2026/04/29/exxon-awards-new-rig-contract-to-noble-at-us375000-day-rate/",
        "Fleet dayrate color ~$375-400k/day is a day-rate datum for the time-series.",
    ),
    A(
        "Yellowtail",
        "2022",
        "SBM Offshore",
        "production_hub",
        "ONE GUYANA FPSO (250 kbopd); $1.75bn financing Jul 2022",
        "",
        "",
        "not_public",
        "",
        "operator",
        "SBM Offshore",
        "https://www.sbmoffshore.com/newsroom/press-releases/2022/21-07-2022/sbm-offshore-completes-us175-billion-financing-one-guyana",
    ),
    A(
        "Yellowtail",
        "2026",
        "SBM Offshore",
        "production_hub",
        "ExxonMobil purchase of FPSO ONE GUYANA (Feb 2026)",
        "2320",
        "2320",
        "point",
        "",
        "operator",
        "SBM Offshore / GlobeNewswire",
        "https://www.globenewswire.com/news-release/2026/02/04/3232326/0/en/FPSO-ONE-GUYANA-Purchase-by-ExxonMobil-Guyana-Completed.html",
        "Largest single Guyana FPSO buyout: $2.32bn.",
    ),
    A(
        "Yellowtail",
        "2021",
        "TechnipFMC",
        "sps",
        "51 EVDT trees + 12 manifolds + controls",
        "500",
        "1000",
        "band",
        "large",
        "operator",
        "TechnipFMC / Upstream",
        "https://www.upstreamonline.com/field-development/exxonmobil-hands-out-big-subsea-hardware-contract-for-guyanas-yellowtail-project/2-1-1098871",
    ),
    A(
        "Yellowtail",
        "2022",
        "TechnipFMC",
        "sps",
        "6 HPHT flexible risers",
        "75",
        "250",
        "band",
        "significant",
        "operator",
        "TechnipFMC / OE Digital",
        "https://www.oedigital.com/news/496219-technipfmc-gets-notice-to-proceed-wins-more-work-at-exxon-s-yellowtail-project-offshore-guyana",
    ),
    A(
        "Yellowtail",
        "2022",
        "Saipem",
        "surf",
        "SURF EPCI ~1,800 m WD",
        "",
        "1100",
        "combined",
        "",
        "operator",
        "Saipem",
        "https://www.saipem.com/en/media/press-releases/2022-01-11/saipem-awarded-two-new-offshore-contracts-australia-and-guyana",
        "~$1.1bn COMBINED with Scarborough (Australia); split not published — upper bound only.",
    ),
    A(
        "Yellowtail",
        "2022",
        "Noble Corporation",
        "drilling_rig",
        "CEA pooled; extensions to 2029 within $1.3bn multi-region backlog adds",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Noble / OilNOW",
        "https://oilnow.gy/news/guyana-rigs-extended-to-2029-as-noble-secures-us1-3b-in-new-contracts/",
    ),
    # ===== US GoM (frame-agreement regime — most values hidden) =====
    A(
        "Anchor",
        "2019",
        "Daewoo Shipbuilding (DSME)",
        "production_hub",
        "Semi FPU hull build (22,000 t, Okpo)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "OE Digital",
        "https://www.oedigital.com/news/473766-chevron-hits-go-on-anchor",
    ),
    A(
        "Anchor",
        "2019",
        "Kiewit Offshore",
        "production_hub",
        "FPU topsides fabrication + integration (Ingleside TX)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "OE Digital",
        "https://www.oedigital.com/news/473766-chevron-hits-go-on-anchor",
    ),
    A(
        "Anchor",
        "2019",
        "OneSubsea (SLB)",
        "sps",
        "Industry-first integrated 20k-psi SPS under 20-yr Chevron MSA",
        "",
        "",
        "not_public",
        "",
        "operator",
        "World Oil",
        "https://www.worldoil.com/news/2019/12/12/chevron-awards-onesubsea-industry-s-first-fully-integrated-20-000-psi-production-system",
        "Premise correction: Anchor SPS = OneSubsea, NOT TechnipFMC.",
    ),
    A(
        "Anchor",
        "2020",
        "Subsea 7",
        "surf",
        "SURF EPCI (flowlines, risers, umbilical install, jumpers)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Subsea 7 / GlobeNewswire",
        "https://www.globenewswire.com/news-release/2020/04/14/2015348/0/en/Subsea-7-awarded-contract-offshore-US-Gulf-of-Mexico.html",
        "Release atypically used NO Subsea7 band word.",
    ),
    A(
        "Anchor",
        "2020",
        "Aker Solutions",
        "surf",
        "~24 km 20k-psi dynamic steel-tube + power umbilicals (20-yr Chevron master)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Aker Solutions",
        "https://www.akersolutions.com/news/news-archive/2020/aker-solutions-wins-20-year-umbilicals-master-order-with-chevron/",
    ),
    A(
        "Anchor",
        "2018",
        "Transocean",
        "drilling_rig",
        "Deepwater Titan — 5-yr (first 20k floater, dual 20k BOPs, ~$455k/day implied)",
        "830",
        "830",
        "backlog",
        "",
        "operator",
        "Transocean",
        "https://www.deepwater.com/news/detail?ID=23251",
        "$830MM backlog (excl mob); the only Anchor award with a public value.",
    ),
    A(
        "Anchor",
        "2021",
        "Boskalis",
        "installation",
        "Heavy transport of FPU hull Okpo->Ingleside (BOKA Vanguard)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Chevron newsroom",
        "https://www.chevron.com/newsroom/2023/q2/offshore-project-to-help-meet-energy-demand",
    ),
    A(
        "Anchor",
        "2020",
        "Oceaneering",
        "other",
        "First 20k-psi hydraulic junction plates + IFLs (20-yr GoM MSA)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "OE Digital",
        "https://www.oedigital.com/news/484071-industry-s-first-oceaneering-s-20-000-psi-equipment-for-chevron-s-anchor-project",
    ),
    A(
        "Ballymore",
        "2022",
        "Subsea 7",
        "installation",
        "SCR + flowline + control system install, 3-well tieback to Blind Faith",
        "50",
        "150",
        "band",
        "sizeable",
        "operator",
        "Subsea 7 / GlobeNewswire",
        "https://www.globenewswire.com/news-release/2022/06/01/2454567/0/en/Subsea-7-awarded-contract-offshore-Gulf-of-Mexico.html",
        "Subsea7 'sizeable' = $50-150MM (publisher-verified).",
    ),
    A(
        "Ballymore",
        "2021",
        "Worley",
        "production_hub",
        "Blind Faith brownfield modifications (eng + procurement)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/projects/ballymore-oil-and-gas-field-gulf-of-mexico-usa/",
    ),
    A(
        "Ballymore",
        "2022",
        "Expro",
        "other",
        "3-yr in-riser 15k ball-valve completion/intervention system",
        "15",
        "15",
        "point",
        "",
        "operator",
        "JPT (SPE)",
        "https://jpt.spe.org/expro-scoops-ballymore-valve-contract",
        "'valued at over $15 million' — the only exact Ballymore award value.",
    ),
    A(
        "Kaskida",
        "2024",
        "Seatrium",
        "production_hub",
        "FPU EPC (4-column semi + single topside module, 80 kbopd)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Seatrium SGX / World Oil",
        "https://worldoil.com/news/2024/12/24/seatrium-awarded-fpu-contract-for-bp-s-kaskida-development-in-gulf-of-mexico/",
    ),
    A(
        "Kaskida",
        "2024",
        "TechnipFMC",
        "sps",
        "Integrated iEPCI: 20k trees + manifolds AND umbilicals/risers/flowlines (single contract)",
        "250",
        "500",
        "band",
        "substantial",
        "operator",
        "TechnipFMC",
        "https://www.technipfmc.com/media/u51ngpkc/tfmc-kaskida-award-press-release.pdf",
        "TechnipFMC 'substantial' = $250-500MM; spans SPS+SURF — do not double-count with a separate SURF row.",
    ),
    A(
        "Kaskida",
        "2025",
        "SBM Offshore",
        "installation",
        "Wet tow + offshore installation of FPU",
        "",
        "",
        "not_public",
        "",
        "operator",
        "OE Digital",
        "https://www.oedigital.com/news/525202-bp-hires-sbm-offshore-to-install-kaskida-fpu-in-gulf-of-america",
    ),
    A(
        "Kaskida",
        "2024",
        "Transocean",
        "drilling_rig",
        "Deepwater Atlas — 365-day from Q2 2028 + option (~$635k/day implied)",
        "232",
        "232",
        "backlog",
        "",
        "operator",
        "Transocean",
        "https://www.deepwater.com/news/detail?ID=28871",
        "$232MM backlog. (Deepwater Invictus $531MM is a separate BP GoM fixture with UNCONFIRMED Kaskida attribution — excluded.)",
    ),
    A(
        "Kaskida",
        "2024",
        "Enbridge",
        "other",
        "Canyon Oil Pipeline + Gathering System (Enbridge builds/owns/operates)",
        "700",
        "700",
        "midstream",
        "",
        "operator",
        "Enbridge",
        "https://www.enbridge.com/media-center/news/details?id=123829&lang=en",
        "$700MM Enbridge midstream investment — OUTSIDE BP's project capex; flagged so E5 does not sum it into coverage.",
    ),
    A(
        "Whale",
        "2019",
        "Sembcorp Marine (Seatrium)",
        "production_hub",
        "EPC topsides + hull (~25,000 t, replicates Vito; delivered Oct 2023)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/sembcorp-marine-to-build-fpu-for-shells-whale-field-in-gulf-of-mexico/",
    ),
    A(
        "Whale",
        "2021",
        "McDermott",
        "surf",
        "EPCIC ~50 km pipeline + 15 km umbilicals, 5 drill centers",
        "",
        "",
        "not_public",
        "",
        "operator",
        "McDermott / PR Newswire",
        "https://www.prnewswire.com/news-releases/mcdermott-completes-epcic-project-in-gulf-of-mexico-302392063.html",
        "Premise correction: Whale SURF = McDermott, NOT Subsea7.",
    ),
    A(
        "Whale",
        "2023",
        "Boskalis",
        "installation",
        "Dry tow of 25,000 t FPU (Singapore->Ingleside) + wet tow",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/shells-new-gulf-of-mexico-platform-arrives-on-boskalis-giant-heavy-transport-vessel/",
    ),
    # ===== International =====
    A(
        "Bacalhau Phase 1",
        "2021",
        "MODEC",
        "production_hub",
        "FPSO EPCI turnkey newbuild (220 kbopd) + first-yr O&M — the largest single award, never valued",
        "",
        "",
        "not_public",
        "",
        "operator",
        "MODEC",
        "https://www.modec.com/news/2021/20210603_pr_bacalhau.html",
    ),
    A(
        "Bacalhau Phase 1",
        "2021",
        "Subsea7 (Subsea Integration Alliance)",
        "surf",
        "Integrated SPS+SURF EPCI, Subsea7 share (140 km risers/flowlines, 40 km umbilicals, T&I)",
        "750",
        "",
        "band",
        "major",
        "operator",
        "OE Digital",
        "https://www.oedigital.com/news/488110-subsea-integration-alliance-confirms-bacalhau-epci-contract",
        "Subsea7 'major' = share > $750MM (open-topped). OneSubsea share within the SIA contract undisclosed.",
    ),
    A(
        "Bacalhau Phase 1",
        "2021",
        "OneSubsea (Subsea Integration Alliance)",
        "sps",
        "19 trees + wellheads/controls within integrated SIA EPCI",
        "",
        "",
        "not_public",
        "",
        "operator",
        "OE Digital",
        "https://www.oedigital.com/news/488110-subsea-integration-alliance-confirms-bacalhau-epci-contract",
    ),
    A(
        "Bacalhau Phase 1",
        "2021",
        "Seadrill",
        "drilling_rig",
        "West Saturn drillship — 4-yr firm + options, 6 wells",
        "380",
        "380",
        "point",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/news/seadrill-380m-drillship-contract-equinor/",
        "'Seadrill's portion ... valued at $380m'.",
    ),
    A(
        "Bacalhau Phase 1",
        "2020",
        "Baker Hughes / Halliburton / Schlumberger",
        "other",
        "Drilling & well services (combined, Nov 2020)",
        "455",
        "455",
        "point",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/projects/bacalhau-oil-field-santos-basin-brazil/",
        "'Drilling and well services contracts worth $455m'.",
    ),
    A(
        "Sangomar Phase 1",
        "2020",
        "MODEC",
        "production_hub",
        "FPSO purchase (EPCC, VLCC conversion, 100 kbopd) — sale to Woodside, price not disclosed",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Woodside ASX 10 Jan 2020",
        "https://www.woodside.com/docs/default-source/asx-announcements/2020-asx/sangomar-field-development-approved.pdf",
    ),
    A(
        "Sangomar Phase 1",
        "2020",
        "Subsea Integration Alliance",
        "sps",
        "Integrated SPS+SURF EPCI incl T&I: 23 wells, 107 km flowlines, 45 km umbilicals",
        "500",
        "750",
        "band",
        "very large",
        "operator",
        "Subsea7 / GlobeNewswire",
        "https://www.globenewswire.com/news-release/2020/01/10/1968794/0/en/Subsea-Integration-Alliance-awarded-contract-offshore-Senegal.html",
        "Subsea7 'very large' = $500-750MM (Subsea7 share; spans SPS+SURF — do not double-count).",
    ),
    A(
        "Sangomar Phase 1",
        "2019",
        "Diamond Offshore",
        "drilling_rig",
        "Ocean BlackRhino (18 firm wells) + Ocean BlackHawk",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/woodside-hires-two-diamond-drillships-for-senegal-operations/",
    ),
    A(
        "Barossa",
        "2021",
        "BW Offshore",
        "production_hub",
        "FPSO BW Opal — LEASE-AND-OPERATE 15-yr firm ($4.6bn firm-period value; ~$2.0bn FPSO capex + lease/opex)",
        "4600",
        "4600",
        "lease_contract",
        "",
        "operator",
        "BW Offshore / GlobeNewswire",
        "https://www.globenewswire.com/news-release/2021/03/23/2198157/0/en/BW-Offshore-Signed-contract-for-Barossa-FPSO.html",
        "$4.6bn is a 15-yr lease+opex value spanning operating costs — NOT comparable to project capex; flagged so E5 excludes it from capex coverage.",
    ),
    A(
        "Barossa",
        "2021",
        "TechnipFMC",
        "sps",
        "Trees/controls/manifolds/wellheads + install support",
        "75",
        "250",
        "band",
        "significant",
        "operator",
        "TechnipFMC / Euro-Petrole",
        "https://www.euro-petrole.com/technipfmc-receives-notice-to-proceed-for-subsea-contract-for-santos-barossa-project-offshore-australia-n-i-22165",
    ),
    A(
        "Barossa",
        "2020",
        "Subsea 7",
        "surf",
        "EPC + T&I 36 km infield flowlines + install client-supplied risers/umbilicals",
        "300",
        "500",
        "band",
        "large",
        "operator",
        "Subsea 7 / GlobeNewswire",
        "https://www.globenewswire.com/news-release/2020/03/03/1993972/0/en/Subsea-7-awarded-contract-offshore-Australia.html",
        "Subsea7 'large' = $300-500MM.",
    ),
    A(
        "Barossa",
        "2019",
        "Allseas",
        "other",
        "Gas Export Pipeline EPCI (262 km, 26-in)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "Santos",
        "https://www.santos.com/news/another-major-barossa-contract-awarded/",
    ),
    A(
        "GranMorgu (Block 58)",
        "2024",
        "SBM Offshore",
        "production_hub",
        "FPSO construct & install (Fast4Ward, 220 kbopd)",
        "",
        "",
        "not_public",
        "",
        "operator",
        "SBM Offshore",
        "https://www.sbmoffshore.com/newsroom/sbm-offshore-awarded-contracts-for-the-granmorgu-field-development/",
    ),
    A(
        "GranMorgu (Block 58)",
        "2024",
        "Technip Energies",
        "production_hub",
        "FPSO topsides EPC",
        "1055",
        "",
        "band",
        "major",
        "operator",
        "Technip Energies",
        "https://www.ten.com/en/media/press-releases/technip-energies-awarded-major-contract-totalenergies-topsides-granmorgu-fpso",
        "T.EN 'major' = > EUR 1bn revenue (~$1,055MM at import FX; open-topped). Currency note: threshold is EUR.",
    ),
    A(
        "GranMorgu (Block 58)",
        "2024",
        "TechnipFMC",
        "sps",
        "Major iEPCI: Subsea 2.0 trees, manifolds + umbilicals/flex jumpers/risers",
        "1000",
        "",
        "band",
        "major",
        "operator",
        "TechnipFMC",
        "https://www.technipfmc.com/en/investors/financial-news-releases/press-release/technipfmc-awarded-major-iepci-contract-for-totalenergies-granmorgu-development-offshore-suriname/",
        "TechnipFMC 'major' = > $1bn (open-topped).",
    ),
    A(
        "GranMorgu (Block 58)",
        "2024",
        "Saipem",
        "surf",
        "SURF EPCI: ~100 km production + 90 km injection lines + flex/umbilicals (install incl.)",
        "1900",
        "1900",
        "point",
        "",
        "operator",
        "Saipem",
        "https://www.saipem.com/en/media/press-releases/2024-11-14/saipem-new-offshore-contract-totalenergies-suriname-19-billion-usd",
        "'The contract is worth 1.9 billion USD' — the largest exact SURF value in the registry; ~18% of $10.5bn gross.",
    ),
    A(
        "GranMorgu (Block 58)",
        "2025",
        "Noble Corporation",
        "drilling_rig",
        "Two 16-well contracts (~1,060 days each): Noble Discoverer + Noble Valiant",
        "753",
        "1050",
        "point",
        "",
        "operator",
        "Noble Corporation Q1 2025 results",
        "https://www.prnewswire.com/news-releases/noble-corporation-plc-announces-first-quarter-2025-results-302440174.html",
        "$753MM firm + up to $297MM performance-linked (LOW=firm 753, HIGH=max 1050).",
    ),
]

STATEMENTS = [
    # Guyana
    S(
        "Liza Phase 1",
        "2017",
        "ExxonMobil / Hess (joint FID)",
        "operator+partner",
        "",
        "gross_capex",
        "4400",
        "USD",
        "partner_sec",
        "Hess / Business Wire",
        "https://www.businesswire.com/news/home/20170616005327/en/Hess-Takes-Final-Investment-Decision-Liza-Phase",
        "'Phase 1 is expected to cost more than $4.4 billion, which includes a lease capitalization cost of about $1.2 billion for the FPSO facility'",
        "Gross incl ~$1.2bn FPSO lease capitalization.",
    ),
    S(
        "Liza Phase 1",
        "2017",
        "Hess",
        "partner",
        "30",
        "net_share",
        "955",
        "USD",
        "partner_sec",
        "Hess / Business Wire",
        "https://www.businesswire.com/news/home/20170616005327/en/Hess-Takes-Final-Investment-Decision-Liza-Phase",
        "'Hess' net share of development costs is forecast to be approximately $955 million'",
        "Net EXCLUDES FPSO lease element: $955/0.30 = $3.18bn ~= gross ex-FPSO $3.2bn.",
    ),
    S(
        "Liza Phase 2",
        "2019",
        "Hess",
        "partner",
        "30",
        "gross_capex",
        "6000",
        "USD",
        "partner_sec",
        "Hess",
        "https://investors.hess.com/news-releases/news-release-details/hess-sanctions-liza-phase-2-development-offshore-guyana",
        "'gross capital cost of approximately $6 billion, including a lease capitalization cost of approximately $1.6 billion for the FPSO'",
        "",
    ),
    S(
        "Liza Phase 2",
        "2019",
        "Hess",
        "partner",
        "30",
        "net_share",
        "1600",
        "USD",
        "partner_sec",
        "Hess",
        "https://investors.hess.com/news-releases/news-release-details/hess-sanctions-liza-phase-2-development-offshore-guyana",
        "'Hess' net share of development costs is forecast to be approximately $1.6 billion'",
        "",
    ),
    S(
        "Payara",
        "2020",
        "ExxonMobil",
        "operator",
        "45",
        "gross_capex",
        "9000",
        "USD",
        "operator",
        "ExxonMobil",
        "https://corporate.exxonmobil.com/news/news-releases/2020/0930_exxonmobil-to-proceed-with-payara-development-offshore-guyana",
        "'The $9 billion development will target an estimated resource base of about 600 million oil-equivalent barrels'",
        "",
    ),
    S(
        "Payara",
        "2020",
        "Hess",
        "partner",
        "30",
        "net_share",
        "1800",
        "USD",
        "partner_sec",
        "Hess / Business Wire",
        "https://www.businesswire.com/news/home/20200930006005/en/Hess-Sanctions-Payara-Development-Offshore-Guyana",
        "'Hess' net share of development costs excluding pre-sanction costs and FPSO purchase cost is forecast to be approximately $1.8 billion'",
        "Phasing disclosed: ~250/450/500/300/225 across 2021-2025.",
    ),
    S(
        "Yellowtail",
        "2022",
        "ExxonMobil",
        "operator",
        "45",
        "gross_capex",
        "10000",
        "USD",
        "operator",
        "ExxonMobil",
        "https://corporate.exxonmobil.com/news/news-releases/2022/0404_exxonmobil-makes-final-investment-decision-on-fourth-guyana-offshore-project",
        "'The $10 billion project will include six drill centers and up to 26 production and 25 injection wells'",
        "",
    ),
    S(
        "Yellowtail",
        "2022",
        "Hess",
        "partner",
        "30",
        "net_share",
        "2300",
        "USD",
        "partner_sec",
        "Hess / Business Wire",
        "https://www.businesswire.com/news/home/20220401005508/en/Hess-Sanctions-Yellowtail-Development-Offshore-Guyana",
        "'Hess' net share of development costs, excluding pre-sanction costs and FPSO purchase cost, is forecast to be approximately $2.3 billion'",
        "Exact reconciliation: $2.3bn/0.30 = $7.67bn ~= $10bn gross - $2.32bn FPSO ($7.68bn). Confirms Hess net EXCLUDES FPSO.",
    ),
    # GoM
    S(
        "Anchor",
        "2019",
        "Chevron",
        "operator",
        "62.86",
        "gross_capex",
        "5700",
        "USD",
        "operator",
        "Chevron (World Oil reprint)",
        "https://www.worldoil.com/news/2019/12/12/chevron-greenlights-its-anchor-20-000-psi-deepwater-project-in-the-gulf-of-mexico",
        "'The initial development of the project will require an investment of approximately $5.7 billion.'",
        "Interests verified 62.86 Chevron / 37.14 Total.",
    ),
    S(
        "Ballymore",
        "2022",
        "Chevron",
        "operator",
        "60",
        "gross_capex",
        "1600",
        "USD",
        "operator",
        "Chevron",
        "https://www.chevron.com/newsroom/2022/q2/chevron-sanctions-ballymore-project-in-deepwater-us-gulf-of-mexico",
        "'will require an investment of approximately $1.6 billion'",
        "",
    ),
    S(
        "Kaskida",
        "2024",
        "BP",
        "operator",
        "100",
        "gross_capex",
        "5000",
        "USD",
        "operator",
        "JPT (SPE) reporting BP 2Q24 call",
        "https://jpt.spe.org/bp-oks-20k-psi-kaskida-project-in-gulf-of-mexico",
        "BP CEO: 'the Kaskida project would cost less than $5 billion'",
        "Upper bound ('less than $5bn'); BP 100% at FID so gross = net.",
    ),
    # International
    S(
        "Bacalhau Phase 1",
        "2021",
        "Equinor",
        "operator",
        "40",
        "gross_capex",
        "8000",
        "USD",
        "operator",
        "Equinor",
        "https://www.equinor.com/news/archive/20210601-final-investment-decision-bacalhau-phase1-brazil",
        "'The investment is approximately 8 billion USD.'",
        "",
    ),
    S(
        "Sangomar Phase 1",
        "2020",
        "Woodside",
        "operator",
        "82",
        "gross_capex",
        "4200",
        "USD",
        "operator",
        "Offshore Engineer",
        "https://www.oedigital.com/news/476949-woodside-partners-in-talks-over-4-2b-sangomar-project-timing",
        "'Woodside, Partners in Talks over $4.2B Sangomar Project Timing'",
        "See cost_revision_trails.csv for the full $4.2->$5.0bn outturn trail.",
    ),
    S(
        "Barossa",
        "2021",
        "Santos",
        "operator",
        "50",
        "gross_capex",
        "3600",
        "USD",
        "operator",
        "Santos",
        "https://www.santos.com/news/santos-announces-fid-on-the-barossa-gas-project-for-darwin-lng/",
        "'a final investment decision (FID) has been taken to proceed with the US$3.6 billion gas and condensate project'",
        "",
    ),
    S(
        "Barossa",
        "2021",
        "SK E&S",
        "partner",
        "37.5",
        "net_share",
        "1400",
        "USD",
        "partner",
        "Korea Herald",
        "http://www.koreaherald.com/view.php?ud=20210330000633",
        "'SK E&S said it will invest 1.6 trillion won ($1.4 billion) over the next five years to develop an Australian gas field'",
        "Cross-check: 0.375 x $3.6bn = $1.35bn ~= $1.4bn stated.",
    ),
    S(
        "Barossa",
        "2021",
        "JERA",
        "partner",
        "12.5",
        "entry_price",
        "300",
        "USD",
        "partner",
        "Santos",
        "https://www.santos.com/news/santos-agrees-sale-of-12-5-interest-in-barossa-project-to-jera/",
        "'total consideration due to Santos at completion expected to be approximately US$300 million'",
        "ENTRY price for the 12.5% interest — NOT a capex share; flagged so E5 does not treat it as net capex.",
    ),
    S(
        "GranMorgu (Block 58)",
        "2024",
        "TotalEnergies",
        "operator",
        "50",
        "gross_capex",
        "10500",
        "USD",
        "operator",
        "TotalEnergies",
        "https://totalenergies.com/news/press-releases/suriname-totalenergies-announces-final-investment-decision-granmorgu",
        "'Total investment is estimated at around $10.5 billion and first oil is expected in 2028'",
        "",
    ),
    S(
        "GranMorgu (Block 58)",
        "2025",
        "APA Corporation",
        "partner",
        "50",
        "carry",
        "1375",
        "USD",
        "partner_sec",
        "APA Corp Form 10-K FY2024 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/1841666/000204026625000007/apa-20241231.htm",
        "'For the first $10 billion of gross capital expenditures, TotalEnergies pays 87.5 percent, and the Company pays 12.5 percent; for the next $5 billion ... 75/25'",
        "Implied APA net ~$1,375MM on $10.5bn gross via the disclosed carry mechanics — a carry, not a flat working-interest share.",
    ),
    S(
        "GranMorgu (Block 58)",
        "2025",
        "Staatsolie",
        "NOC",
        "20",
        "net_share",
        "2400",
        "USD",
        "regulator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/noc-raising-funds-to-cover-its-share-of-costs-for-totalenergies-led-12-2b-oil-project-off-suriname/",
        "'the firm's share amounts to $2.4 billion'",
        "Staatsolie states a $12.2bn TOTAL (vs TotalEnergies/APA $10.5bn) — likely includes drilling/extra scope; noted as a gross-figure discrepancy.",
    ),
]


def main() -> int:
    with open(CURATED / "contract_awards.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=AWARD_FIELDS)
        w.writeheader()
        w.writerows(AWARDS)
    with open(
        CURATED / "project_cost_statements.csv", "w", newline="", encoding="utf-8"
    ) as fh:
        w = csv.DictWriter(fh, fieldnames=STMT_FIELDS)
        w.writeheader()
        w.writerows(STATEMENTS)
    ap = sorted({a["PROJECT"] for a in AWARDS})
    sp = sorted({s["PROJECT"] for s in STATEMENTS})
    valued = [a for a in AWARDS if a["VALUE_BASIS"] not in ("not_public",)]
    print(
        f"contract_awards: {len(AWARDS)} rows / {len(ap)} projects "
        f"({len(valued)} with a value or band)"
    )
    print(f"project_cost_statements: {len(STATEMENTS)} rows / {len(sp)} projects")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
