# ABOUTME: E1 (#1024) import — 40 pre-validated sanctioned projects into sanctioned_projects.csv
# ABOUTME: Every row carries verbatim quote + second source (in NOTES) per the #1019-baked intake standard.
import csv
from pathlib import Path

PATH = Path("data/modules/cost/curated/sanctioned_projects.csv")
D = "2026-07-15"


def row(
    project,
    operator,
    region,
    country,
    wd,
    fid,
    foil,
    capex,
    basis,
    wells,
    dev,
    host,
    res,
    title,
    url,
    quote,
    second,
    notes,
    conf,
    prio,
    offshore=True,
    actual="",
    surf="",
    peak="",
    boe="",
):
    return {
        "PROJECT": project,
        "OPERATOR": operator,
        "REGION": region,
        "COUNTRY": country,
        "WATER_DEPTH_M": wd,
        "FID_YEAR": fid,
        "FIRST_OIL_YEAR": foil,
        "SANCTIONED_CAPEX_USD_MM": capex,
        "ACTUAL_COST_USD_MM": actual,
        "CAPEX_BASIS": basis,
        "WELL_COUNT": wells,
        "DEVELOPMENT_TYPE": dev,
        "HOST_TYPE": host,
        "SURF_KM": surf,
        "PEAK_PRODUCTION_BOEPD": peak,
        "RECOVERABLE_RESOURCE_MMBOE": res,
        "USD_PER_BOE": boe,
        "SOURCE_TITLE": title,
        "SOURCE_URL": url,
        "PAGE_REFERENCE": "see quoted_text",
        "QUOTED_TEXT": quote,
        "ACCESSED_DATE": D,
        "CONFIDENCE": conf,
        "SOURCE_PRIORITY": prio,
        "NOTES": f"{notes} Second source: {second}. Imported per #1024 (E1 expansion, second-sourced at intake).",
        "SCOPE_IS_OFFSHORE_ONLY": "True" if offshore else "False",
    }


NEW = [
    # ---- Europe ----
    row(
        "Mariner",
        "Statoil (now Equinor)",
        "UK North Sea",
        "United Kingdom",
        "110",
        "2012",
        "2019",
        "7000.0",
        "gross project investments stated by operator at FID (Dec 2012), full development incl. PDQ platform + FSU + jack-up rig; heavy oil",
        "",
        "new_host_fixed",
        "fixed PDQ platform + 850k bbl FSU",
        "250",
        "Equinor press release, 21 Dec 2012 — Statoil makes investment decision for the Mariner project",
        "https://www.equinor.com/news/archive/2012/12/21/21DecMariner",
        "'The project entails investments of more than USD 7 billion and is the largest new offshore development in the UK in more than a decade.'",
        "Offshore Energy — https://www.offshore-energy.biz/statoil-makes-fid-for-7-bln-mariner-development-uk/ ($7bn)",
        "First oil planned 2017, actual Aug 2019; outturn ~$7.7bn reported at startup (trade press); reserves later downgraded ~180 mmboe (2020). Operator archive page renders partial text; USD sentence preserved in reprints.",
        "high",
        "press_release",
    ),
    row(
        "Kraken",
        "EnQuest",
        "UK North Sea",
        "United Kingdom",
        "110",
        "2013",
        "2017",
        "3200.0",
        "full-cycle gross capex at sanction (Nov 2013) per USD-reporting operator, restated at first oil ('down from $3.2 billion'); heavy oil; sanction release itself was GBP-only",
        "25",
        "new_host_fpso",
        "leased converted FPSO (Armada Kraken, Bumi Armada)",
        "137",
        "EnQuest press release, 26 Jun 2017 — Kraken First Oil",
        "https://www.enquest.com/media/press-releases/article/kraken-first-oil",
        "'The gross capital costs of the development are currently estimated to be approximately $2.5 billion, down from $3.2 billion'",
        "Offshore Energy — https://www.offshore-energy.biz/enquest-shaves-100-million-off-kraken-costs/ (revision reporting)",
        "Cost trail: $3.2bn (2013 sanction) -> $2.5bn (first oil 2017) -> ~$2.3bn (FY2017). Leased-FPSO basis noted.",
        "high",
        "press_release",
        actual="2500.0",
    ),
    row(
        "Martin Linge (ex-Hild)",
        "Total (Equinor operator from 2018)",
        "Norwegian North Sea",
        "Norway",
        "115",
        "2012",
        "2021",
        "4200.0",
        "gross development investment stated by operator at launch (Feb 2012): 'US$4.2 billion (NOK 25.6 billion)' — rare operator-stated USD for a Norwegian PDO (French operator)",
        "",
        "new_host_fixed",
        "fixed integrated platform + FSO, power from shore",
        "190",
        "TotalEnergies press release, 2 Feb 2012 — Total launches the Hild field development",
        "https://totalenergies.com/media/news/press-releases/total-launches-hild-field-development-north-sea-norway",
        "'This development will represent an investment of US$4.2 billion (NOK 25.6 billion)'",
        "Offshore Technology — https://www.offshore-technology.com/projects/martin-linge-field-north-sea-norway/",
        "Severe overrun/delay: first oil planned end-2016, actual Jun 2021; outturn ~NOK 63bn (NPD/Equinor); Total sold its 51% to Equinor for $1.45bn (2018).",
        "high",
        "press_release",
    ),
    row(
        "Culzean",
        "Maersk Oil (Total operator from 2018)",
        "UK North Sea",
        "United Kingdom",
        "",
        "2015",
        "2019",
        "4500.0",
        "operator's own parenthetical USD at sanction: 'around GBP 3bn (USD 4.5bn)'; HPHT gas-condensate",
        "",
        "new_host_fixed",
        "three bridge-linked fixed platforms + FSO",
        "250",
        "Maersk Oil announcement (Offshore Energy reprint; Maersk Oil site defunct post-Total acquisition)",
        "https://www.offshore-energy.biz/uk-approves-maersk-oils-culzean-field-development/",
        "'Maersk Oil and its co-venturers, JX Nippon and BP (Britoil) are investing around GBP 3bn (USD 4.5 bn)'",
        "World Oil — https://www.worldoil.com/news/2015/8/31/maersk-gets-uk-approval-for-45-billion-culzean-field-development ($4.5bn)",
        "Resources 250-300 mmboe; first gas Jun 2019 on schedule; estimate later cut ~$500MM to ~$4bn (Dec 2016). USD is the operator's parenthetical equivalent.",
        "medium",
        "secondary_operator_confirmed",
    ),
    row(
        "Golden Eagle Area",
        "Nexen",
        "UK North Sea",
        "United Kingdom",
        "",
        "2011",
        "2014",
        "3300.0",
        "total gross cost to develop per operator board-sanction release (Apr 2011): 'US$3.3 billion, Nexen share ~US$1.2 billion'; CAUTION: operator's Oct 2011 release labels the same figure C$3.3bn (2011 CAD/USD parity); GBP 2bn is the anchor",
        "20",
        "new_host_fixed",
        "two fixed platforms (PUQ bridge-linked to wellhead)",
        "140",
        "Nexen board-sanction release, 27 Apr 2011 (Offshore Energy reprint)",
        "https://www.offshore-energy.biz/nexen-bod-approves-golden-eagle-development-in-uk-north-sea/",
        "'The total cost to develop Golden Eagle is US$3.3 billion, with Nexen's share at approximately US$1.2 billion.'",
        "Nexen via GlobeNewswire, 27 Oct 2011 — https://www.globenewswire.com/news-release/2011/10/27/1362468/0/en/Nexen-Receives-Regulatory-Approval-for-Major-UK-North-Sea-Development.html ('GBP 2 billion (C$3.3 billion)')",
        "20 wells (16 platform + 4 subsea); 140 mmboe 2P; first oil Nov 2014. Currency-label discrepancy documented in basis.",
        "medium",
        "secondary_operator_confirmed",
    ),
    # ---- Latin America ----
    row(
        "BM-C-33 (Raia Manta/Raia Pintada)",
        "Equinor",
        "Brazil - Campos pre-salt",
        "Brazil",
        "2900",
        "2023",
        "2028",
        "9000.0",
        "gross project investment at FID (May 2023), FPSO gas-condensate development incl. gas export to shore",
        "",
        "new_host_fpso",
        "FPSO ~126,000 boepd + 16 MMcm/d gas processing",
        "1000",
        "Equinor press release, 8 May 2023 — Final investment decision for BM-C-33",
        "https://www.equinor.com/news/20230508-final-investment-decision-bm-c-33-brazil",
        "'The investment is of approximately USD 9 billion.'",
        "NS Energy — https://www.nsenergybusiness.com/news/equinor-takes-fid-9bn-bm-c-33-gas-and-condensate-project-brazil/ ($9bn)",
        "Equinor 35 (op) / Repsol Sinopec 35 / Petrobras 30. Start-up planned 2028; recoverable >1,000 MMboe.",
        "high",
        "press_release",
    ),
    row(
        "Trion",
        "Woodside (60%) / Pemex (40%)",
        "Mexico - Perdido",
        "Mexico",
        "2500",
        "2023",
        "2028",
        "7200.0",
        "forecast total capital expenditure at FID (Jun 2023), 100% gross incl. all 24 wells; EXCLUDES the forecast lease amount for the leased FSO (operator footnote)",
        "24",
        "new_host_semi",
        "semi FPU 100,000 bpd + leased FSO 950k bbl",
        "479",
        "Woodside ASX announcement, 20 Jun 2023 — Woodside approves investment in Trion development",
        "https://www.woodside.com/docs/default-source/asx-announcements/2023-asx/woodside-approves-investment-in-trion-development.pdf",
        "'The forecast total capital expenditure is US$7.2 billion (US$4.8 billion Woodside share including capital carry of PEMEX of approximately US$460 million)'",
        "JPT (SPE) — https://jpt.spe.org/woodside-takes-fid-on-7-2-billion-trion-project-in-mexico ($7.2bn)",
        "479 MMboe 2C gross; Woodside carries Pemex ~$460MM (partner-share datum); first oil target 2028; CNH approved FDP 2023.",
        "high",
        "press_release",
    ),
    row(
        "Peregrino Phase 2",
        "Statoil (now Equinor)",
        "Brazil - Campos",
        "Brazil",
        "120",
        "2014",
        "2022",
        "3500.0",
        "gross investment at investment approval (Dec 2014) / dev-plan submission (Feb 2015): new WHP-C platform tied to existing FPSO; SHALLOW water (120 m); later re-scoped and delivered below $3bn",
        "21",
        "new_host_fixed",
        "WHP-C fixed platform tied to existing FPSO Peregrino",
        "250",
        "Equinor press release, 27 Feb 2015 — Development plan for Peregrino Phase II submitted",
        "https://www.equinor.com/news/archive/2015/02/27/27FebPeregrino",
        "'The project entails investments of approximately USD 3,5 billion.'",
        "Marine Technology News — https://www.marinetechnologynews.com/news/statoil-submits-peregrino-509758 (~$3.5bn)",
        "RARE downward outturn: paused, improvement program, restart Apr 2016 with ~$500MM cut, delivered within ~$3bn; onstream 13 Oct 2022. Operatorship to PRIO announced Nov 2025.",
        "high",
        "press_release",
    ),
    row(
        "Papa-Terra (BC-20)",
        "Petrobras (op, 62.5%) / Chevron (37.5%)",
        "Brazil - Campos",
        "Brazil",
        "1190",
        "2010",
        "2013",
        "5200.0",
        "gross total project cost estimate at FID (Jan 2010), attributed to partner Chevron's FID release",
        "",
        "new_host_tlp",
        "TLWP P-61 (Brazil's first TLP) + FPSO P-63 (140,000 bpd)",
        "380",
        "Chevron press release, 27 Jan 2010 (reproduction verified; official copy at SEC 8-K exhibit)",
        "https://www.sec.gov/Archives/edgar/data/0000093410/000095012310048910/f55717exv99w1.htm",
        "'Chevron holds a 37.5 per cent interest in the Petrobras-operated Papa Terra project, which they estimate will cost $5.2 billion.'",
        "Rigzone — https://www.rigzone.com/news/oil_gas/a/86445/Chevron_Charges_Ahead_with_52B_Papa_Terra_Project ($5.2bn)",
        "Cautionary outturn: severe underperformance vs 380 MMbbl basis; Chevron exited; sold to 3R Petroleum (2022). First oil Nov 2013.",
        "medium",
        "sec_filing",
    ),
    row(
        "Frade (BC-4)",
        "Chevron (op, 51.7%)",
        "Brazil - Campos",
        "Brazil",
        "1128",
        "2006",
        "2009",
        "2400.0",
        "total planned gross investment at FID (Jun 2006) per partner Sojitz's FID release; FPSO under SBM lease-and-operate (charter treatment noted)",
        "19",
        "new_host_fpso",
        "FPSO Frade 100,000 bpd (SBM charter)",
        "300",
        "Sojitz Corporation FID release, 22 Jun 2006 (via Wayback Machine)",
        "https://web.archive.org/web/2020/https://www.sojitz.com/en/news/2006/06/20060622-1.php",
        "'The total planned investment in the project is US$2.4 billion.'",
        "Offshore Technology — https://www.offshore-technology.com/projects/fradefieldcamposbasi/ ('partners invested approximately $3bn' — outturn)",
        "Trail: $2.4bn plan (2006) -> ~$3bn invested (trade press); 2011 spill halted drilling; PRIO now operates.",
        "medium",
        "press_release",
    ),
    row(
        "Maromba",
        "BW Energy (100%)",
        "Brazil - Campos",
        "Brazil",
        "150",
        "2025",
        "2027",
        "1500.0",
        "total gross investment at FID (May 2025): ~$1.2bn initial development + ~$0.3bn second drilling campaign; $274MM of capex under FPSO sale-leaseback (10-yr fixed dayrate $120,500); SHALLOW water (150 m)",
        "12",
        "new_host_fpso",
        "wellhead platform + refurbished FPSO, 60,000 bpd plateau",
        "",
        "BW Energy via GlobeNewswire, 5 May 2025 — BW Energy Makes FID on Maromba field development",
        "https://www.globenewswire.com/news-release/2025/05/05/3073754/0/en/BW-Energy-Makes-FID-on-Maromba-field-development-in-Brazil.html",
        "'Total investments of USD ~1.5 billion, split USD ~1.2 billion for the initial development and a further USD ~0.3 billion for the secondary drilling campaign'",
        "JPT (SPE) — https://jpt.spe.org/bw-energy-reaches-fid-on-maromba-project-offshore-brazil ($1.5bn)",
        "500 MMbbl oil in place (recoverable not disclosed); 6+6 wells; first oil planned end-2027. The $120,500/day FPSO leaseback rate is a day-rate datum for the time-series.",
        "high",
        "press_release",
    ),
    row(
        "Atlanta Full Field (Definitive System)",
        "Enauta (100%, now Brava Energia)",
        "Brazil - Santos post-salt",
        "Brazil",
        "1550",
        "2022",
        "2024",
        "1200.0",
        "board-approved full-development investment (Feb 2022) incl. ~$500MM production unit and $100MM post-startup; FPSO later sold to Yinson with 15-yr charter (mixed capex/charter outturn noted)",
        "6",
        "new_host_fpso",
        "FPSO Atlanta (ex-OSX-2, purchased $80MM + converted; 50,000 bpd)",
        "",
        "Enauta disclosure carried by Offshore Energy (fetch Enauta/Brava material-fact PDF for belt-and-braces)",
        "https://www.offshore-energy.biz/all-systems-go-for-full-development-of-enautas-brazillian-field-including-fpso-deal-with-yinson/",
        "'the approved investment for the full development of the field is $1.2 billion, including the $100 million to be injected after production starts and $500 million, referring to the production unit.'",
        "Rigzone — https://www.rigzone.com/news/enauta_approves_12b_full_development_of_atlanta_field-23-feb-2022-168022-article/ ($1.2bn)",
        "6 wells at startup growing to 10 by 2029; first oil ~end-2024.",
        "medium",
        "secondary_operator_confirmed",
    ),
    # ---- Asia-Pacific / ME / Med / Caspian ----
    row(
        "Gorgon (incl. Jansz-Io)",
        "Chevron",
        "Australia - Carnarvon",
        "Australia",
        "200",
        "2009",
        "2016",
        "37000.0",
        "first-phase total estimated project costs per operator 10-K (FY2011): 3 LNG trains + domgas + CO2 sequestration; INTEGRATED LNG — includes onshore liquefaction",
        "",
        "subsea_tieback",
        "subsea wells (Gorgon ~200m, Jansz-Io ~1350m) to onshore 15.6 mtpa LNG, Barrow Island",
        "",
        "Chevron Corporation Form 10-K FY2011 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/93410/000095012312002976/f60351e10vk.htm",
        "'Total estimated project costs for the first phase of development are $37 billion.'",
        "IndustryWeek — https://www.industryweek.com/operations/energy-management/article/21971352/chevrons-54-billion-gorgon-lng-project-starts-production (~$54bn outturn)",
        "Trail: $37bn FID (Sep 2009) -> +$15bn (Dec 2012) -> ~$54bn outturn at first LNG (Mar 2016).",
        "high",
        "sec_filing",
        offshore=False,
    ),
    row(
        "Wheatstone (incl. Iago)",
        "Chevron",
        "Australia - Carnarvon",
        "Australia",
        "",
        "2011",
        "2017",
        "29000.0",
        "foundation-phase total estimated project costs per operator 10-K (FY2011): offshore processing platform + two onshore LNG trains; INTEGRATED LNG",
        "",
        "new_host_fixed",
        "offshore platform + Ashburton North 8.9 mtpa LNG",
        "",
        "Chevron Corporation Form 10-K FY2011 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/93410/000095012312002976/f60351e10vk.htm",
        "'Total estimated project costs for the first phase of development are $29 billion.' (Wheatstone section)",
        "S&P Global — https://www.spglobal.com/commodityinsights/en/market-insights/latest-news/natural-gas/092611-chevron-approves-australias-a29-bil-wheatstone-lng-project (A$29bn, ~USD parity Sep 2011)",
        "FID 26 Sep 2011; first LNG Oct 2017; outturn ~$34bn per trade press (unverified, not imported).",
        "high",
        "sec_filing",
        offshore=False,
    ),
    row(
        "Greater Enfield",
        "Woodside",
        "Australia - Carnarvon",
        "Australia",
        "700",
        "2016",
        "2019",
        "1900.0",
        "total gross project cost per partner Mitsui's FID release (US$1.9bn; US$800MM net to MEPAU at 40%); subsea tieback to existing FPSO",
        "",
        "subsea_tieback",
        "existing Ngujima-Yin FPSO (31 km tieback)",
        "69",
        "Mitsui & Co. press release (40% partner), 27 Jun 2016",
        "https://www.mitsui.com/jp/en/release/2016/1219556_8910.html",
        "'about US$1.9 billion (US$800 million net to MEPAU)'",
        "Rigzone — https://www.rigzone.com/news/woodsidemitsui_jv_approves_19_greater_enfield_project_off_wa-27-jun-2016-145291-article/ ($1.9bn)",
        "First oil mid-2019, on schedule and under budget per operator. WD 550-850 m.",
        "high",
        "press_release",
    ),
    row(
        "Kikeh",
        "Murphy Oil (80%)",
        "Malaysia - Sabah deepwater",
        "Malaysia",
        "1330",
        "2004",
        "2007",
        "1900.0",
        "gross development costs per operator 10-K FY2004, per board- and government-approved FDP, INCLUDING $0.5bn of capitalized FPSO lease costs",
        "",
        "new_host_fpso",
        "Kikeh FPSO + spar dry-tree unit (Block K)",
        "",
        "Murphy Oil Corporation Form 10-K FY2004 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/717423/000119312505052706/d10k.htm",
        "'A field development plan, as approved by the Company's Board of Directors and the Malaysian authorities, calls for gross development costs of $1.9 billion, which includes $.5 billion of lease costs for an FPSO.'",
        "Offshore Technology — https://www.offshore-technology.com/projects/kikeh-floating-production-storage-offloading-development/ (~$1.4bn excl. leased FPSO, consistent)",
        "Malaysia's first deepwater field; first oil Aug 2007.",
        "high",
        "sec_filing",
    ),
    row(
        "Tamar (Phase 1)",
        "Noble Energy",
        "Mediterranean",
        "Israel",
        "1676",
        "2010",
        "2013",
        "3000.0",
        "total first-phase development cost per operator 10-K FY2011 ($3.0bn gross, $1.1bn net to Noble)",
        "5",
        "new_host_fixed",
        "Tamar fixed platform + ~150 km tieback to Ashdod onshore terminal",
        "1667",
        "Noble Energy Inc Form 10-K FY2011 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/72207/000114036112006454/form10k.htm",
        "'The total first phase development cost of Tamar is estimated at $3.0 billion ($1.1 billion net).'",
        "Offshore Technology — https://www.offshore-technology.com/projects/tamar-field/ ($4.6bn FULL project incl. later scope — not phase-1-comparable, noted)",
        "First gas Mar 2013, on schedule and budget per operator; ~10 tcf (~1,667 mmboe at 6:1).",
        "high",
        "sec_filing",
    ),
    row(
        "Shah Deniz Stage 2 (incl. SCPX)",
        "BP",
        "Caspian",
        "Azerbaijan",
        "550",
        "2013",
        "2018",
        "28000.0",
        "total cost of SD2 + South Caucasus Pipeline Expansion per partner Statoil SEC 6-K; INCLUDES pipeline expansion and onshore Sangachal processing (excludes TANAP/TAP)",
        "26",
        "new_host_fixed",
        "two bridge-linked platforms + 26 subsea wells",
        "",
        "Statoil ASA Form 6-K, 17 Dec 2013 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/1140625/000114062513000101/sto131217_6-k.htm",
        "'The total cost of the Shah Deniz stage 2 and SCP Expansion projects will be around USD 28 billion.'",
        "NS Energy — https://www.nsenergybusiness.com/projects/shah-deniz-gas-field-development/ (~$28bn)",
        "FID 17 Dec 2013; first gas Jun 2018; 16 bcma plateau.",
        "high",
        "sec_filing",
        offshore=False,
    ),
    row(
        "Azeri Central East (ACG)",
        "BP",
        "Caspian",
        "Azerbaijan",
        "140",
        "2019",
        "2024",
        "6000.0",
        "development cost per operator sanction release (new 48-slot platform, up to 100,000 bpd); SHALLOW water (140 m)",
        "",
        "new_host_fixed",
        "48-slot production/drilling/quarters platform",
        "300",
        "BP press release, 19 Apr 2019",
        "https://www.bp.com/en/global/corporate/news-and-insights/press-releases/bp-and-partners-sanction-6-billion-dollar-azeri-central-east-development-offshore-azerbaijan.html",
        "'The $6 billion development includes a new offshore platform and facilities designed to process up to 100,000 barrels of oil per day.'",
        "World Oil — https://www.worldoil.com/news/2019/4/19/bp-partners-sanction-6-billion-azeri-central-east-development-offshore-azerbaijan ($6bn)",
        "First production Apr 2024 (target was 2023); up to 300 MMbbl.",
        "high",
        "press_release",
    ),
    row(
        "KG-D6 integrated (R-Cluster + Satellites + MJ)",
        "Reliance Industries (op) + bp",
        "India - Krishna Godavari",
        "India",
        "2000",
        "2017",
        "2020",
        "5000.0",
        "COMBINED investment across THREE FIDs (R-Series Jun 2017, Satellites Apr 2018, MJ Jun 2019) per operator/bp joint release: 'circa INR 35,000 crore (US$5 billion)'; never split per project",
        "",
        "subsea_tieback",
        "R-Cluster/Satellites tiebacks to existing KG-D6 infrastructure; MJ via FPSO Ruby",
        "500",
        "bp press release (MJ sanction), Jun 2019 — Reliance and bp sanction third phase of integrated KG D6 development",
        "https://www.bp.com/en/global/corporate/news-and-insights/press-releases/reliance-and-bp-sanction-third-phase-of-integrated-kg-d6-development.html",
        "'Together the three projects are expected to develop a total of about 3 trillion cubic feet (tcf) of discovered gas resources with a total investment of circa INR 35,000 crore (US$5 billion).'",
        "Ocean News & Technology — https://oceannews.com/news/energy/reliance-and-bp-announces-the-sanction-of-the-mj-project-offshore-india/ (US$5bn)",
        "First gas: R-Cluster Dec 2020 (Asia's deepest, ~2,000 m+), Satellites Apr 2021, MJ 2023. 3 tcf ≈ 500 mmboe. COMBINED-BASIS row — do not attribute to a single project.",
        "medium",
        "press_release",
    ),
    row(
        "KG-DWN-98/2 Cluster-2",
        "ONGC",
        "India - Krishna Godavari",
        "India",
        "413",
        "2016",
        "2024",
        "5076.4",
        "board-approved FDP capital expenditure per operator release: USD 5,076.37MM (INR 34,012 crore), Cluster 2A+2B",
        "35",
        "new_host_fpso",
        "Armada Sterling V FPSO + gas processing platform + subsea tiebacks to shore",
        "",
        "ONGC press release — Board approves FDP for Cluster 2 of KG-DWN-98/2",
        "https://ongcindia.com/web/hi/w/ongc-board-approves-field-development-plan-for-development-of-cluster-2-fields-of-deep-water-nelp-block-kg-dwn-98-2",
        "'capital expenditure of USD 5,076.37 million (equivalent to INR 34,012 Crore)'",
        "NS Energy — https://www.nsenergybusiness.com/projects/cluster-2-field-development-kg-dwn-98-2-block-bay-of-bengal/ ($5.07bn)",
        "FDP approved 2016; heavily delayed — first oil Jan 2024 (plan was 2019/2020). 35 wells (15P+12WI 2A; 8 gas 2B); FPSO moored at 413 m.",
        "high",
        "press_release",
    ),
    row(
        "North Field East (NFE)",
        "QatarEnergy",
        "Middle East - Qatar",
        "Qatar",
        "",
        "2021",
        "2026",
        "28750.0",
        "total project cost stated by operator CEO at FID: 4 LNG mega-trains (32 mtpa) + associated facilities; ONSHORE-HEAVY integrated LNG with offshore wellhead platforms",
        "",
        "new_host_fixed",
        "offshore wellhead platforms feeding 4 onshore trains at Ras Laffan",
        "",
        "QatarEnergy FID announcement (Al-Kaabi statement) via Energy Connects, Feb 2021",
        "https://www.energyconnects.com/news/gas-lng/2021/february/qatar-petroleum-takes-fid-on-north-field-east-project/",
        "'The total cost of the NFE project will be 28.75 billion dollars.'",
        "Offshore Technology — https://www.offshore-technology.com/news/qatar-petroleum-makes-fid-on-28-7bn-north-field-east-project/ ($28.7bn)",
        "FID Feb 2021; first LNG slipped to 2026; boosts Qatar 77 -> 110 mtpa.",
        "medium",
        "secondary_operator_confirmed",
        offshore=False,
    ),
    # ---- US GoM ----
    row(
        "Atlantis (Phase 1)",
        "BP",
        "US GOM - Green Canyon",
        "USA",
        "2150",
        "2002",
        "2007",
        "2000.0",
        "pre-sanction gross estimate FLOOR: 'in excess of US$2 billion' per 44% partner BHP 6-K (May 2002 FEED/long-lead approval, ahead of full 2002 sanction)",
        "",
        "new_host_semi",
        "moored semi-submersible PQ",
        "575",
        "BHP Billiton Form 6-K, 3 May 2002 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/811809/000081180902000069/atlantis.txt",
        "'The gross capital cost is expected to be in excess of US$2 billion (BHP Billiton share approximately US$1 billion).'",
        "OGJ — https://www.ogj.com/drilling-production/article/17248925/bp-raises-atlantis-reserves-estimate-moves-forward-on-development-planning (BP share >$1bn at 56%, consistent)",
        "FLOOR value. First oil Oct 2007 (delayed from 2005). 575 MMboe gross 2P per BHP.",
        "medium",
        "sec_filing",
    ),
    row(
        "Tahiti (Phase 1)",
        "Chevron",
        "US GOM - Green Canyon",
        "USA",
        "1250",
        "2005",
        "2009",
        "2700.0",
        "phase-1 investment stated by 17% partner Total (SEC 6-K) AT FIRST OIL (May 2009) — effectively phase-1 outturn; no FID-time public figure exists; excludes Phase 2 waterflood",
        "6",
        "new_host_spar",
        "truss spar",
        "450",
        "Total S.A. Form 6-K exhibit — Start-up of production of the Tahiti field, 6 May 2009 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/879764/000095012309010394/y03090exv99w6.htm",
        "'The first phase of the field development consists of a floating spar production system producing from six subsea wells, representing an investment of 2.7 billion US dollars.'",
        "OGJ — https://www.ogj.com/drilling-production/article/17278151/tahiti-field-gulfs-deepest-production-starts-up ($2.7bn)",
        "Startup slipped ~1 yr (2007 mooring-shackle metallurgy). 400-500 MMboe (midpoint recorded). Chevron 58 / StatoilHydro 25 / Total 17.",
        "medium",
        "sec_filing",
    ),
    row(
        "Shenzi",
        "BHP Billiton",
        "US GOM - Green Canyon",
        "USA",
        "1310",
        "2006",
        "2009",
        "4400.0",
        "gross full-field development cost THROUGH 2015 at Jun-2006 sanction (BHP net share US$1.94bn)",
        "15",
        "new_host_tlp",
        "TLP",
        "375",
        "BHP Billiton 6-K — Shenzi briefing paper, Jun 2006 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/0000811809/000081180906000077/shenzibriefingpaper.pdf",
        "'The company's estimated gross costs for the full field development through 2015 is approximately US$4.4 billion.'",
        "Offshore Magazine — https://www.offshore-mag.com/regional-reports/article/16792070/bhp-sanctions-shenzi-development ($1.94bn BHP net, consistent)",
        "First oil Mar 2009. BHP 44 / BP 28 / Hess 28. 350-400 MMboe (midpoint).",
        "high",
        "sec_filing",
    ),
    row(
        "Jack/St. Malo (initial phase)",
        "Chevron",
        "US GOM - Walker Ridge",
        "USA",
        "2134",
        "2010",
        "2014",
        "7500.0",
        "gross total project cost of the INITIAL development phase at Oct-2010 FID, per operator 10-K",
        "",
        "new_host_semi",
        "semi hub FPU (170,000 bpd), Lower Tertiary",
        "500",
        "Chevron Corporation Form 10-K FY2010 (SEC)",
        "https://www.sec.gov/Archives/edgar/data/0000093410/000095012311017688/f56670e10vk.htm",
        "'Total project costs for the initial phase of development are estimated at $7.5 billion and start-up is expected in 2014.'",
        "Offshore Energy — https://www.offshore-energy.biz/usa-chevron-sanctions-jackst-malo-project-in-the-gulf-of-mexico/ (~$7.5bn)",
        "FID 21 Oct 2010; first oil Dec 2014; recoverable 'in excess of 500 MMboe' (floor). Three subsea drill centers.",
        "high",
        "sec_filing",
    ),
    row(
        "Big Foot",
        "Chevron",
        "US GOM - Walker Ridge",
        "USA",
        "1585",
        "2010",
        "2018",
        "4000.0",
        "gross project cost at Dec-2010 sanction; never publicly restated after the 2015 tendon-installation failure (trade ~$5bn unattributed, not imported)",
        "",
        "new_host_tlp",
        "extended TLP, dry trees, on-board rig",
        "200",
        "Chevron sanction release, 16 Dec 2010 (verbatim reprint fetched at gCaptain)",
        "https://gcaptain.com/chevron-sanctions-foot-project/",
        "'today announced it has sanctioned development of its $4 billion Big Foot project'",
        "Offshore Energy — https://www.offshore-energy.biz/usa-chevron-sanctions-4-billion-big-foot-project-in-the-deepwater-gulf-of-mexico/ ($4bn)",
        "First oil slipped 2014 -> Nov 2018 (May-2015 tendon failure). >200 MMboe (floor). Sanction confirmed (no figure) in Chevron 10-K FY2010.",
        "medium",
        "secondary_operator_confirmed",
    ),
    row(
        "Tubular Bells",
        "Hess",
        "US GOM - Mississippi Canyon",
        "USA",
        "1340",
        "2011",
        "2014",
        "2300.0",
        "gross development cost at Oct-2011 sanction; EXCLUDES the third-party-owned leased spar FPS (Williams Gulfstar One, ~$420MM/5yr per Hess 10-K) and export commitments",
        "5",
        "new_host_spar",
        "third-party-owned classic spar (Gulfstar One)",
        "120",
        "Hess sanction announcement, 25 Oct 2011 (investors.hess.com bot-blocked; verbatim carried in fetched OGJ coverage)",
        "https://investors.hess.com/news-releases/news-release-details/hess-announces-plan-develop-tubular-bells-field-gulf-mexico",
        "'Hess Corp. plans to proceed with the $2.3 billion Tubular Bells deepwater oil and gas project in the Gulf of Mexico.' (OGJ rendering)",
        "gCaptain — https://gcaptain.com/hess-plans-development-tubular/ ($2.3bn)",
        "First oil Nov 2014; >120 MMboe (floor); Hess 57.14 / Chevron 42.86. 3 producers + 2 injectors initially.",
        "medium",
        "secondary_operator_confirmed",
    ),
    row(
        "Julia (initial phase)",
        "ExxonMobil",
        "US GOM - Walker Ridge",
        "USA",
        "2134",
        "2013",
        "2016",
        "4000.0",
        "gross capital cost FLOOR 'more than $4 billion' at FID for the initial 6-well phase (subsea tieback to Jack/St. Malo FPU)",
        "6",
        "subsea_tieback",
        "tieback to Jack/St. Malo semi FPU",
        "",
        "ExxonMobil press release, 7 May 2013 — ExxonMobil to Develop Julia Oil Field",
        "https://investor.exxonmobil.com/company-information/press-releases/detail/625/exxonmobil-to-develop-julia-oil-field-in-the-gulf-of-mexico",
        "'Capital cost for the project, which is expected to begin oil production in 2016, is estimated to be more than $4 billion.'",
        "World Pipelines — https://www.worldpipelines.com/business-news/08052013/exxonmobil-commences-julia-field-development_1928/ (>$4bn)",
        "FLOOR value. First oil Apr 2016; ~6 bn bbl in place; Statoil 50% partner (its release gives no figure).",
        "high",
        "press_release",
    ),
    row(
        "Atlantis Phase 3",
        "BP",
        "US GOM - Green Canyon",
        "USA",
        "2150",
        "2019",
        "2020",
        "1300.0",
        "gross investment for the Phase-3 subsea expansion ONLY (8 wells into existing facility) at Jan-2019 sanction; BP-attributed via fetched Rigzone coverage (bp.com bot-blocked)",
        "8",
        "subsea_tieback",
        "existing Atlantis semi-submersible",
        "",
        "BP sanction announcement, 8 Jan 2019 (BP-attributed in Rigzone coverage)",
        "https://www.bp.com/en/global/corporate/news-and-insights/press-releases/bp-plans-for-significant-growth-in-deepwater-gulf-of-mexico.html",
        "'BP has approved a $1.3 billion expansion for the Atlantis Phase 3 development in the U.S. Gulf of Mexico, the company announced Tuesday.' (Rigzone)",
        "Offshore Magazine — https://www.offshore-mag.com/drilling-completion/article/16790624/bp-sanctions-atlantis-expansion-in-the-gulf-of-mexico ($1.3bn)",
        "Sanction confirmed (no figure) in BP 4Q18 6-K. First oil Jul 2020, ahead of schedule; +38,000 boe/d gross peak.",
        "medium",
        "secondary_operator_confirmed",
    ),
    row(
        "Shenzi North",
        "BHP (now Woodside)",
        "US GOM - Green Canyon",
        "USA",
        "1310",
        "2021",
        "2023",
        "544.0",
        "approved capital expenditure on a 100% (gross) basis at Aug-2021 board approval; two-well subsea tie-in",
        "2",
        "subsea_tieback",
        "existing Shenzi TLP",
        "",
        "BHP Annual Report 2021 filed as Form 6-K (SEC)",
        "https://www.sec.gov/Archives/edgar/data/811809/000119312521272106/d201084d6k.htm",
        "'an investment of US$544 million for the Shenzi North development in the US Gulf of Mexico... The capital expenditure approved represents a 100 per cent share interest.'",
        "Oilfield Technology — https://www.oilfieldtechnology.com/offshore-and-subsea/06082021/bhp-approves-shenzi-north-project-in-gulf-of-mexico/ ($544MM)",
        "First production Sep 2023 (Woodside), ahead of CY2024 target. BHP 72 / Repsol 28.",
        "high",
        "sec_filing",
    ),
    # ---- Africa ----
    row(
        "Kaombo",
        "Total",
        "West Africa",
        "Angola",
        "1700",
        "2014",
        "2018",
        "16000.0",
        "capital expenditure to reach full capacity per operator FID release (Apr 2014), after $4bn optimization from $20bn",
        "59",
        "new_host_fpso",
        "two converted-VLCC FPSOs (115,000 bpd each), Block 32",
        "650",
        "TotalEnergies press release, 14 Apr 2014 — Total launches the development of Kaombo",
        "https://totalenergies.com/media/news/press-releases/angola-total-launches-development-kaombo-ultra-deep-offshore-project",
        "'the project's capital expenditure to reach full capacity was reduced by 4 billion dollars to 16 billion dollars'",
        "World Oil — https://www.worldoil.com/news/2014/4/14/total-launches-kaombo-ultra-deep-project-offshore-angola ($16bn)",
        "First oil Kaombo Norte Jul 2018, Sul 2019; ~300 km subsea lines; WD 1,400-1,900 m.",
        "high",
        "press_release",
    ),
    row(
        "Moho Nord (incl. Phase 1bis)",
        "Total",
        "West Africa",
        "Republic of the Congo",
        "800",
        "2013",
        "2017",
        "10000.0",
        "joint investment for Moho Bilondo Phase 1bis + Moho Nord per operator FID release (Mar 2013)",
        "45",
        "new_host_tlp",
        "Congo's first TLP + Likouf FPU; Ph1bis tied back to Alima FPU",
        "",
        "TotalEnergies press release, 22 Mar 2013 — Total launches Moho Nord development",
        "https://totalenergies.com/media/news/press-releases/total-lance-le-developpement-de-moho-nord-en-republique-du-congo",
        "'The joint development represents an investment of US$10 billion.'",
        "Offshore Energy — https://www.offshore-energy.biz/total-makes-10-bln-fid-for-moho-nord-development-congo/ ($10bn)",
        "WD 450-1,200 m; 11 wells Ph1bis + 34 Moho Nord; Moho Nord first oil Mar 2017; 100,000 boe/d.",
        "high",
        "press_release",
    ),
    row(
        "Mozambique LNG (Area 1)",
        "TotalEnergies (FID by Anadarko)",
        "East Africa",
        "Mozambique",
        "",
        "2019",
        "2029",
        "20000.0",
        "total post-FID investment per operator statement (Jul 2020); INCLUDES onshore 2-train 13.1 mtpa liquefaction plant at Afungi",
        "",
        "subsea_tieback",
        "subsea-to-shore + onshore LNG (2 trains, 13.1 mtpa)",
        "",
        "TotalEnergies news, 17 Jul 2020 — Total announces the signing of Mozambique LNG project financing",
        "https://totalenergies.com/media/news/news/total-announces-signing-mozambique-lng-project-financing",
        "'Mozambique LNG represents a total post-FID investment of 20 B$.'",
        "Offshore Energy — https://www.offshore-energy.biz/5-billion-loan-dusting-off-the-cobwebs-from-totalenergies-stalled-20b-lng-project/ ($20bn)",
        "FID Jun 2019 (Anadarko); Total acquired operatorship Sep 2019; force majeure 2021-2024, restart approved; first LNG now ~2029; restart cost pressure = OPEN revision trail.",
        "high",
        "press_release",
        offshore=False,
    ),
    row(
        "West Nile Delta",
        "BP",
        "Mediterranean",
        "Egypt",
        "450",
        "2015",
        "2017",
        "12000.0",
        "estimated investment of ~$12bn by BP and partner (DEA) at final agreements (Mar 2015), BP-attributed; gas-to-shore, includes onshore processing plants",
        "",
        "subsea_tieback",
        "subsea tiebacks to onshore processing (Taurus/Libra, Giza/Fayoum, Raven)",
        "940",
        "BP final-agreements announcement, 6 Mar 2015 (BP-attributed; bp.com blocked to fetcher; carried by World Oil)",
        "https://www.worldoil.com/news/2015/3/6/bp-finalizes-12-billion-deal-to-develop-egypt-s-west-nile-delta",
        "'BP announced Friday that it has signed the final agreements of the West Nile Delta (WND) project... with an estimated investment of around $12 billion by BP and its partner.'",
        "Hart Energy — https://www.hartenergy.com/news/bp-finalizes-12-billion-west-nile-delta-gas-fields-development-deal-102901 ($12bn)",
        "5 tcf gas + 55 MMbbl condensate (~940 mmboe); first gas May 2017 (Taurus/Libra), Raven 2021; WD ~100-800 m.",
        "medium",
        "secondary_operator_confirmed",
        offshore=False,
    ),
    row(
        "TEN (Tweneboa-Enyenra-Ntomme)",
        "Tullow Oil",
        "West Africa",
        "Ghana",
        "1500",
        "2013",
        "2016",
        "4000.0",
        "sanction-approved gross capex to first oil per operator executive ('the $4-billion figure we approved at sanction'); leased FPSO separate; ~$4.9bn overall incl. post-first-oil phases",
        "24",
        "new_host_fpso",
        "FPSO Prof. John Evans Atta Mills (80,000 bpd)",
        "300",
        "Tullow executive statement carried by Offshore Magazine — TEN extends Ghana's, Tullow's deepwater credentials",
        "https://www.offshore-mag.com/deepwater/article/16754742/ten-extends-ghanas-tullows-deepwater-credentials",
        "'our capital costs to first oil will come in under the $4-billion figure we approved at sanction'",
        "Offshore Technology — https://www.offshore-technology.com/projects/ten-development-project-deepwater-tano-ghana/ ($4.9bn total incl. later phases, noted)",
        "Ghana approved the development plan 30 May 2013; first oil Aug 2016, 39 months after sanction, within budget. Tullow 47.175% op.",
        "medium",
        "secondary_operator_confirmed",
    ),
    row(
        "Jubilee Phase 1",
        "Tullow (unit operator) / Kosmos (technical dev operator)",
        "West Africa",
        "Ghana",
        "1100",
        "2009",
        "2010",
        "3300.0",
        "Phase-1 development cost per partner Kosmos's first-oil release ($3.3bn); original budget $3.15bn, Tullow-reported final ~$3.35bn (trail)",
        "17",
        "new_host_fpso",
        "FPSO Kwame Nkrumah (120,000 bpd)",
        "",
        "Kosmos Energy first-oil release, Dec 2010 (carried by Offshore Energy)",
        "https://www.offshore-energy.biz/kosmos-energy-celebrates-first-oil-from-3-3-billion-jubilee-field-development-offshore-ghana/",
        "'$3.3 billion world-class Jubilee Field development offshore the Republic of Ghana'",
        "Offshore Magazine — https://www.offshore-mag.com/production/article/16763668/jubilee-brings-ghana-into-deepwater-fold ($3.35bn final vs $3.15bn original)",
        "Plan approved Jul 2009; first oil 15 Dec 2010 (~3.5 yrs from discovery); Ph1 wells 9 producers + 5 WI + 3 GI.",
        "medium",
        "secondary_operator_confirmed",
        actual="3350.0",
    ),
    row(
        "Zinia Phase 2",
        "Total",
        "West Africa",
        "Angola",
        "900",
        "2018",
        "2021",
        "1200.0",
        "project budget per operator FID release (May 2018); short-cycle brownfield subsea tieback on Block 17",
        "9",
        "subsea_tieback",
        "tieback to existing Pazflor FPSO",
        "",
        "TotalEnergies press release, 28 May 2018 — Total launches Zinia 2 development",
        "https://totalenergies.com/media/news/press-releases/angola-total-launches-zinia-2-development-deep-offshore-block-17",
        "'Zinia 2 comprises nine wells in water depths ranging from 600 to 1,200 meters, tied back to the Pazflor FPSO with a budget of US$1.2 billion.'",
        "World Oil — https://www.worldoil.com/news/2018/5/28/total-takes-fid-for-zinia-2-development-offshore-angola ($1.2bn)",
        "40,000 bpd capacity; production started 2021.",
        "high",
        "press_release",
    ),
    row(
        "Mafumeira Sul",
        "Chevron (CABGOC)",
        "West Africa",
        "Angola",
        "60",
        "2013",
        "2016",
        "5600.0",
        "total project cost per operator FID release (Feb 2013, Business Wire); SHALLOW water (60 m), Block 0 — included for basin completeness, not deepwater",
        "50",
        "new_host_fixed",
        "two wellhead platforms + central processing/compression complex",
        "",
        "Chevron FID release via Business Wire, 6 Feb 2013",
        "https://www.businesswire.com/news/home/20130206005555/en/Chevron-Makes-Final-Investment-Decision-on-Mafumeira-Sul-Project-Offshore-Angola",
        "'the $5.6 billion Mafumeira Sul project is the second stage of development of the Mafumeira Field located in Block 0.'",
        "Offshore Energy (reproduction) — https://www.offshore-energy.biz/chevron-makes-fid-on-mafumeira-sul-offshore-angola/ ($5.6bn)",
        "Early production Feb 2016, CPF onstream 2017 (slip from 2015 target); peak 110,000 bpd + 10,000 bpd LPG. Chevron 39.2 / Sonangol 41 / Total 10 / Eni 9.8.",
        "high",
        "press_release",
    ),
    row(
        "Baleine (Phases 1-3 programme)",
        "Eni",
        "West Africa",
        "Ivory Coast",
        "1200",
        "2022",
        "2023",
        "10000.0",
        "PROGRAMME total across three phases 2023-2027 stated by Ivory Coast's Energy Minister (regulator/concessionaire tier), NOT a single-FID capex; Eni's Phase 3 FID release (May 2026) discloses no figure",
        "",
        "new_host_fpso",
        "FPSO Baleine (ex-Firenze, Ph1) + FPSO Petrojarl Kong (Ph2) + newbuild FPSO (Ph3)",
        "",
        "Ivory Coast Energy Minister Coulibaly statement via MarineLink, 23 Nov 2023",
        "https://www.marinelink.com/news/eni-invest-billion-ivory-coast-baleine-509675",
        "'Eni will invest $10 billion in the development of the Baleine field offshore Ivory Coast, which will take place in three phases from 2023 to 2027'",
        "Offshore Technology — https://www.offshore-technology.com/news/eni-baleine-field-investment/ ($10bn)",
        "Ph1 first oil Aug 2023 (fast-track, <2 yrs from discovery); Ph2 onstream Dec 2024; Ph3 FID 25 May 2026 (figure-free: https://www.eni.com/en-IT/media/press-release/2026/05/eni-and-partners-approve-investment-for-baleine-phase-3-in-c-te-d-ivoire.html). COMBINED-PROGRAMME basis.",
        "medium",
        "regulator_document",
    ),
]

with open(PATH, newline="") as fh:
    reader = csv.DictReader(fh)
    fields = reader.fieldnames
    rows = list(reader)

existing = {r["PROJECT"] for r in rows}
dupes = [n["PROJECT"] for n in NEW if n["PROJECT"] in existing]
if dupes:
    raise SystemExit(f"duplicate project names: {dupes}")

# --- upgrades to existing rows ---
for r in rows:
    if r["PROJECT"] == "Coral South FLNG":
        r["SANCTIONED_CAPEX_USD_MM"] = "7000.0"
        r["CAPEX_BASIS"] = (
            "total development capex, upstream + midstream incl. newbuild FLNG, "
            "estimated at c.$7 billion — stated by 10% PARTNER Galp in its investor "
            "announcement AT FID (1 Jun 2017); operator Eni's release remains figure-free"
        )
        r["SOURCE_TITLE"] = (
            "Galp investor announcement, 1 Jun 2017 — Coral South Final Investment Decision"
        )
        r["SOURCE_URL"] = (
            "https://www.galp.com/corp/en/investors/publications-and-announcements/"
            "investor-announcements/investor-announcement/id/721/coral-south-final-investment-decision"
        )
        r["QUOTED_TEXT"] = (
            "'Total development capex for upstream and midstream is estimated at c.$7 billion (bn)'"
        )
        r["ACCESSED_DATE"] = D
        r["CONFIDENCE"] = "medium"
        r["SOURCE_PRIORITY"] = "press_release"
        r["NOTES"] = (
            r["NOTES"]
            + " UPGRADED per #1024 (E1): partner-Galp FID figure imported ($7.0bn), "
            "consistent with the Eni financing-implied ~$7.8bn; second source SPE/JPT "
            "https://www.spe.org/en/print-article/?art=3131. First LNG Nov 2022 on schedule/budget."
        )
    if r["PROJECT"] == "Bacalhau Phase 1" and not r["FIRST_OIL_YEAR"]:
        r["FIRST_OIL_YEAR"] = "2025"
    if r["PROJECT"] == "Bacalhau Phase 1":
        r["NOTES"] = (
            r["NOTES"]
            + " E1 corroboration: production started 15 Oct 2025 (Equinor release)."
        )
    if r["PROJECT"] == "Mad Dog Phase 2 (Argos)":
        r["SOURCE_TITLE"] = "BHP Billiton Form 6-K half-year results, Feb 2017 (SEC)"
        r["SOURCE_URL"] = (
            "https://www.sec.gov/Archives/edgar/data/0000811809/000119312517049179/d341376d6k.htm"
        )
        r["QUOTED_TEXT"] = (
            "'The project cost has more than halved since 2013 with a revised field development "
            "concept leading to significant cost reductions and is now estimated to be US$9 billion "
            "on a 100 per cent basis (US$2.2 billion BHP Billiton share).'"
        )
        r["ACCESSED_DATE"] = D
        r["CONFIDENCE"] = "high"
        r["SOURCE_PRIORITY"] = "sec_filing"
        r["NOTES"] = (
            r["NOTES"]
            + " SOURCE UPGRADED per #1024: BHP 6-K (SEC) replaces the secondary "
            "Offshore-Technology profile as primary."
        )

rows.extend(NEW)
rows.sort(key=lambda r: (int(r["FID_YEAR"] or 0), r["PROJECT"]))

with open(PATH, "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=fields)
    w.writeheader()
    w.writerows(rows)
print(f"imported {len(NEW)} new rows; total {len(rows)} projects")
