# ABOUTME: E3 (#1026) — append tranche-2 contract awards to contract_awards.csv + Big Foot outturn trail.
# ABOUTME: 17 projects across Guyana later-phases / West Africa / North Sea / GoM legacy; deterministic, dedup-guarded.
"""
import_e3_2026_07_15_award_tranche2
===================================

Extends the award registry (built for 12 anchor projects in E2/#1025) to 17 more,
from the #1026 tranche-2 research. Same rules as ``build_award_registry.py``:

- bands stored as low/high from the contractor's published definition (never a midpoint);
- ``lease_contract`` (Kraken BW charter), ``midstream`` (Enbridge export), ``combined``
  (Diamond two-rig), ``backlog`` (rig contracts) and ``not_public`` flags keep the
  reconciliation harness (E5) from double-counting or over-crediting;
- a foreign-currency award with no official USD (Kvaerner NOK, Aker NOK) is ``not_public``
  in USD with the local figure in the note — never a silent FX conversion;
- an integrated iEPCI that spans SPS+SURF+install (Rosebank, Tiber) is recorded ONCE
  with a note, never triple-counted.

Also adds the Big Foot cost-revision trail surfaced by the GoM pass ($4bn FID -> $5.1bn
final, +28%) to ``cost_revision_trails.csv`` via a small append.

Idempotent: an award row is skipped if (PROJECT, CONTRACTOR, ASSET_CLASS, AWARD_YEAR)
already exists.
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CURATED = ROOT / "data" / "modules" / "cost" / "curated"
D = "2026-07-15"

AWARD_FIELDS = [
    "PROJECT",
    "AWARD_YEAR",
    "CONTRACTOR",
    "ASSET_CLASS",
    "SCOPE_DESC",
    "VALUE_LOW_MM",
    "VALUE_HIGH_MM",
    "VALUE_BASIS",
    "BAND_WORD",
    "PROVENANCE",
    "SOURCE_TITLE",
    "SOURCE_URL",
    "ACCESSED_DATE",
    "NOTES",
]


def A(
    project,
    year,
    contractor,
    asset,
    scope,
    low,
    high,
    basis,
    band,
    prov,
    title,
    url,
    notes="",
):
    return dict(
        zip(
            AWARD_FIELDS,
            [
                project,
                year,
                contractor,
                asset,
                scope,
                low,
                high,
                basis,
                band,
                prov,
                title,
                url,
                D,
                notes,
            ],
        )
    )


NP = ""  # not-public value shorthand

AWARDS = [
    # ===== West Africa (Total/Chevron) =====
    A(
        "Kaombo",
        "2014",
        "Saipem",
        "production_hub",
        "EPCI two converted-VLCC FPSOs (Norte + Sul): topsides, mooring, hookup, commissioning",
        "3000",
        "3000",
        "point",
        "",
        "operator",
        "Saipem — awarded FPSO contracts in Angola worth more than 4 billion",
        "https://www.saipem.com/en/media/press-releases/2014-04-16/saipem-awarded-fpso-contracts-angola-worth-more-4-billion",
        "EPCI portion ~$3bn; the release's '>$4bn' includes a separate ~$1bn 7-yr O&M (opex, excluded).",
    ),
    A(
        "Kaombo",
        "2014",
        "Aker Solutions",
        "sps",
        "Subsea production system: 20 manifolds + 65 vertical subsea wellsets, controls, tie-in",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Aker Solutions — subsea production system for Total's Kaombo",
        "https://www.akersolutions.com/news/news-archive/2014/aker-solutions-wins-contract-to-deliver-subsea-production-system-for-totals-kaombo-development-in-angola/",
        "Aker stated NOK 14bn (~$2.3bn); no official USD, so not counted in USD coverage.",
    ),
    A(
        "Kaombo",
        "2014",
        "Technip / Heerema alliance",
        "surf",
        "Lump-sum SURF EPCI: 18 rigid risers, ~300 km flowlines, ~115 km umbilicals ('largest SURF ever')",
        "3500",
        "3500",
        "point",
        "",
        "operator",
        "Offshore Magazine — Technip/Heerema land giant Kaombo SURF contract",
        "https://www.offshore-mag.com/subsea/article/16783185/technip-heerema-land-giant-kaombo-surf-contract",
        "Heerema heavy-lift/pipelay install folded into this lump sum.",
    ),
    A(
        "Kaombo",
        "2014",
        "Ocean Rig (drillship Skyros)",
        "drilling_rig",
        "6-yr drilling contract, Block 32 development wells",
        "1300",
        "1300",
        "backlog",
        "",
        "operator",
        "Petroleum Africa / OEDigital",
        "https://www.petroleumafrica.com/total-tags-ocean-rigs-skyros-for-angola-drilling/",
        "",
    ),
    A(
        "Moho Nord (incl. Phase 1bis)",
        "2013",
        "Hyundai Heavy Industries",
        "production_hub",
        "EPC Likouf FPU (62,000 t, 100 kbopd)",
        "1300",
        "1300",
        "point",
        "",
        "operator",
        "Hart Energy — Hyundai wins $2 billion Moho Nord FPU/TLP contracts",
        "https://www.hartenergy.com/news/hyundai-wins-2-billion-moho-nord-fpu-tlp-contracts-95125",
        "",
    ),
    A(
        "Moho Nord (incl. Phase 1bis)",
        "2013",
        "Hyundai Heavy Industries",
        "production_hub",
        "EPC integrated TLP (14,600 t hull + topsides), Congo's first TLP",
        "700",
        "700",
        "point",
        "",
        "operator",
        "Hart Energy — Hyundai wins $2 billion Moho Nord FPU/TLP contracts",
        "https://www.hartenergy.com/news/hyundai-wins-2-billion-moho-nord-fpu-tlp-contracts-95125",
        "Two production_hub rows (FPU + TLP) — this project has both a floater and a platform.",
    ),
    A(
        "Moho Nord (incl. Phase 1bis)",
        "2013",
        "Technip",
        "surf",
        "EPSCI 230 km rigid + 23 km flexibles + 50 km umbilicals ('largest subsea Technip executes on its own')",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Offshore Energy — Technip nets largest subsea contract for Moho Nord",
        "https://www.offshore-energy.biz/technip-nets-largest-subsea-contract-for-moho-nord-off-congo/",
        "Reported >EUR 500m; no verbatim USD/EUR figure — not counted.",
    ),
    A(
        "Moho Nord (incl. Phase 1bis)",
        "2014",
        "Fugro",
        "other",
        "5-yr ROV services & subsea tooling",
        "100",
        "100",
        "point",
        "",
        "operator",
        "OEDigital — Fugro in Moho Nord subsea gig",
        "https://www.oedigital.com/news/453051-fugro-in-moho-nord-subsea-gig",
        "",
    ),
    A(
        "Zinia Phase 2",
        "2018",
        "Subsea 7",
        "surf",
        "EPCI ~36 km flowlines + ~21 km umbilicals -> Pazflor FPSO",
        "150",
        "300",
        "range",
        "",
        "operator",
        "Offshore Energy / NS Energy",
        "https://www.nsenergybusiness.com/news/contracts/subsea-7-awarded-contract-for-1-2bn-zinia-2-field-development-offshore-angola/",
        "'substantial' is Total's operator language (not a Subsea7 band); NS Energy attached a $150-300m range.",
    ),
    A(
        "Zinia Phase 2",
        "2018",
        "TechnipFMC",
        "sps",
        "9 subsea trees + wellheads + controls",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "TechnipFMC — subsea contract for Total Zinia 2",
        "https://www.technipfmc.com/en/investors/financial-news-releases/press-release/technipfmc-awarded-a-subsea-contract-for-the-total-zinia-2-field/",
        "",
    ),
    A(
        "Mafumeira Sul",
        "2012",
        "Saipem (Petromar JV)",
        "surf",
        "EPCI offshore tie-ins + onshore pipeline to Malongo",
        "325",
        "325",
        "point",
        "",
        "operator",
        "Saipem — new offshore contracts worth $350 million",
        "https://www.saipem.com/en/media/press-releases/2012-06-29/saipem-awarded-new-ec-offshore-contracts-worth-350-million",
        "$325m of the bundled ~$350m Angola+Nigeria release.",
    ),
    A(
        "Mafumeira Sul",
        "2013",
        "DSME + Mustang/Wood Group",
        "production_hub",
        "Platforms EPC: central production complex (3 bridge-linked) + 2 wellhead platforms",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "2B1st Consulting",
        "https://2b1stconsulting.com/chevron-to-proceed-with-angola-mafumeira-project-expansion/",
        "",
    ),
    A(
        "Mafumeira Sul",
        "2013",
        "McDermott",
        "production_hub",
        "EPC 148-man Living Quarters Platform",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/projects/mafumeira-sul-project/",
        "",
    ),
    # ===== Guyana Stabroek later phases (ExxonMobil) =====
    A(
        "Uaru",
        "2023",
        "TechnipFMC",
        "sps",
        "44 subsea trees + 12 manifolds + controls (first Subsea 2.0 in Guyana)",
        "500",
        "1000",
        "band",
        "large",
        "operator",
        "TechnipFMC / OceanNews",
        "https://oceannews.com/news/subsea-and-survey/technipfmc-awarded-major-subsea-contract-for-exxonmobil-s-guyana-uaru-project/",
        "",
    ),
    A(
        "Uaru",
        "2023",
        "Saipem",
        "surf",
        "EPCI subsea structures/risers/flowlines/umbilicals ~2,000 m",
        "500",
        "1000",
        "band",
        "large",
        "operator",
        "Saipem — authorization to proceed final phase Uaru",
        "https://www.saipem.com/en/media/press-releases/2023-05-04/saipem-authorization-proceed-final-phase-uaru-project-guyana-0",
        "",
    ),
    A(
        "Uaru",
        "2023",
        "MODEC",
        "production_hub",
        "FPSO Errea Wittu — EPC + charter/O&M (MODEC charter model, NOT SBM); topsides sub-let to Seatrium",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "MODEC / World Oil",
        "https://www.worldoil.com/news/2024/5/6/seatrium-secures-fpso-errea-wittu-contract-from-modec-for-exxonmobil-operated-uaru-field-offshore-guyana/",
        "Correction: Uaru FPSO is MODEC, not SBM.",
    ),
    A(
        "Uaru",
        "2023",
        "Noble Corporation",
        "drilling_rig",
        "Stabroek CEA drillship fleet drills Uaru wells; dayrates ~$420-500k/day",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "OilNOW / Offshore Energy",
        "https://www.offshore-energy.biz/noble-rig-duo-and-stena-drillship-on-oil-gas-exploration-mission-for-exxonmobil-off-guyana/",
        "",
    ),
    A(
        "Whiptail",
        "2024",
        "TechnipFMC",
        "sps",
        "48 subsea trees + 12 manifolds + controls",
        "500",
        "1000",
        "band",
        "large",
        "operator",
        "TechnipFMC / Business Wire",
        "https://www.businesswire.com/news/home/20240415018073/en/TechnipFMC-Awarded-Large-Subsea-Contract-for-ExxonMobil-Guyanas-Whiptail-Project",
        "",
    ),
    A(
        "Whiptail",
        "2024",
        "Saipem",
        "surf",
        "EPCI subsea production facility ~2,000 m (press: up to ~$1.5bn)",
        "750",
        "1500",
        "range",
        "",
        "operator",
        "World Oil",
        "https://www.worldoil.com/news/2024/4/15/saipem-to-proceed-with-1-5-billion-subsea-contract-following-sanctioning-of-exxonmobil-s-whiptail-oil-project-offshore-guyana/",
        "Press-disclosed range (~$1.5bn upper), not a Saipem band word.",
    ),
    A(
        "Whiptail",
        "2024",
        "SBM Offshore",
        "production_hub",
        "FPSO Jaguar (Fast4Ward 7th hull) construct + install",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "SBM Offshore",
        "https://www.sbmoffshore.com/newsroom/sbm-offshore-awarded-contracts-for-exxonmobil-guyanas-fpso-jaguar/",
        "$1.5bn project financing (Nov 2024) is a size proxy, not the award value.",
    ),
    A(
        "Hammerhead",
        "2025",
        "TechnipFMC",
        "sps",
        "Subsea 2.0 trees + manifolds + controls (production + water injection)",
        "250",
        "500",
        "band",
        "substantial",
        "operator",
        "TechnipFMC",
        "https://www.technipfmc.com/media/pbvnpu5m/tfmc-hammerhead-award-release.pdf",
        "",
    ),
    A(
        "Hammerhead",
        "2025",
        "Saipem",
        "surf",
        "EPCI SURF + gas export system ~1,000 m (LNTP Apr 2025, full Sep 2025)",
        "500",
        "500",
        "point",
        "",
        "operator",
        "Saipem",
        "https://www.saipem.com/en/media/press-releases/2025-09-26/saipem-receives-authorization-proceed-execution-hammerhead-offshore",
        "Press-reported 'roughly $500 million'.",
    ),
    A(
        "Hammerhead",
        "2025",
        "MODEC",
        "production_hub",
        "FPSO Hammerhead — FEED + EPCI via LNTP (~150 kbopd)",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "MODEC",
        "https://www.modec.com/news/2025/20250421_pr_Hammerhead.html",
        "MODEC charter model, not SBM.",
    ),
    # ===== North Sea =====
    A(
        "Martin Linge (ex-Hild)",
        "2012",
        "Technip + Samsung consortium",
        "production_hub",
        "EPC platform topsides (~25,000 t) + 95-cabin living quarters",
        "1250",
        "1250",
        "point",
        "",
        "operator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/technip-samsung-to-supply-topsides-for-marting-linge-platform-norway/",
        "Technip ~$780m + Samsung ~$470m.",
    ),
    A(
        "Martin Linge (ex-Hild)",
        "2012",
        "Kvaerner",
        "production_hub",
        "EPSC eight-legged steel jacket",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "gCaptain",
        "https://gcaptain.com/kvaerner-wins-billion-contract/",
        "Kvaerner stated NOK 1.2bn (~$0.2bn); no official USD, not counted.",
    ),
    A(
        "Martin Linge (ex-Hild)",
        "2012",
        "Subsea 7",
        "surf",
        "EPCI SURF (umbilicals, risers, flowlines)",
        "800",
        "800",
        "point",
        "",
        "operator",
        "2B1st Consulting",
        "https://2b1stconsulting.com/total-awarded-main-packages-on-martin-linge-in-norway/",
        "",
    ),
    A(
        "Martin Linge (ex-Hild)",
        "2012",
        "Maersk Drilling (Intrepid jack-up)",
        "drilling_rig",
        "4-yr firm ultra-harsh jack-up drilling",
        "550",
        "550",
        "backlog",
        "",
        "operator",
        "Baird Maritime",
        "https://www.bairdmaritime.com/offshore/maersk-drilling-names-worlds-largest-jack-up-rig",
        "",
    ),
    A(
        "Mariner",
        "2013",
        "Subsea 7",
        "surf",
        "EPIC 38.6 km rigid flowlines + flexible riser systems",
        "170",
        "170",
        "point",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/projects/mariner-area-development-north-sea-uk/",
        "",
    ),
    A(
        "Mariner",
        "2013",
        "Noble Corporation (Lloyd Noble CJ70 jack-up)",
        "drilling_rig",
        "4-yr drilling services (new ultra-high-spec jack-up)",
        "655",
        "655",
        "backlog",
        "",
        "operator",
        "Noble / PR Newswire",
        "https://www.prnewswire.com/news-releases/noble-receives-contract-award-for-new-ultra-high-specification-jackup-to-be-constructed-for-mariner-project-207336501.html",
        "",
    ),
    A(
        "Mariner",
        "2013",
        "Odfjell Drilling",
        "drilling_rig",
        "Platform drilling services (GBP 160m)",
        "245",
        "245",
        "point",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/projects/mariner-area-development-north-sea-uk/",
        "GBP 160m, publisher-stated ~$245m.",
    ),
    A(
        "Mariner",
        "2012",
        "Daewoo (DSME)",
        "production_hub",
        "EPC PDQ platform topside modules",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Equinor",
        "https://www.equinor.com/news/archive/2012/12/21/21DecMariner",
        "",
    ),
    A(
        "Culzean",
        "2015",
        "Sembcorp Marine (SMOE)",
        "production_hub",
        "EPC CPF topsides + 2 bridges + WHP + ULQ topsides (>$1bn incl. long-lead)",
        "1000",
        "1000",
        "point",
        "",
        "operator",
        "Splash247",
        "https://splash247.com/sembcorp-marine-secures-1bn-epc-contract-from-maersk-oil/",
        "",
    ),
    A(
        "Culzean",
        "2015",
        "Subsea 7",
        "surf",
        "SURF 52 km gas export to CATS + condensate line + tie-ins (>$150m)",
        "150",
        "150",
        "point",
        "",
        "operator",
        "Subsea World News",
        "https://subseaworldnews.com/2015/09/01/subsea-7-wins-culzean-surf-prize/",
        "",
    ),
    A(
        "Culzean",
        "2016",
        "Maersk Drilling (Highlander jack-up)",
        "drilling_rig",
        "5-yr, 6 HPHT production wells (incl. $9m mobilization)",
        "420",
        "420",
        "backlog",
        "",
        "operator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/maersk-drillings-new-jack-up-rig-named-in-scotland/",
        "",
    ),
    A(
        "Culzean",
        "2015",
        "Heerema Fabrication",
        "production_hub",
        "P&C two jackets (CPF + ULQ) + wellhead jacket",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Heerema",
        "https://hfg.heerema.com/projects/oil-gas-industry/culzean-cpf-ulq",
        "",
    ),
    A(
        "Kraken",
        "2013",
        "Bumi Armada",
        "production_hub",
        "Bareboat charter FPSO Armada Kraken + O&M, 8-yr firm",
        "1400",
        "1400",
        "lease_contract",
        "",
        "operator",
        "Bumi Armada Berhad",
        "https://www.bumiarmada.com/bumi-armada-signs-kraken-contract-worth-usd-1-4-billion-rm-4-6-billion/",
        "8-yr firm charter (lease + O&M) spanning opex — NOT capex-comparable, like Barossa BW Opal.",
    ),
    A(
        "Kraken",
        "2014",
        "Technip",
        "surf",
        "EPCI 50 km rigid + umbilicals + risers, 3 drill centres",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Offshore Magazine",
        "https://www.offshore-mag.com/subsea/article/16782595/enquest-selects-technip-for-large-subsea-contract",
        "Source calls it 'large' descriptively; no value or Technip band figure.",
    ),
    A(
        "Kraken",
        "2013",
        "SPX",
        "other",
        "Subsea hydraulic / water-injection pump equipment",
        "22",
        "22",
        "point",
        "",
        "operator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/spx-to-supply-pumps-for-enquests-kraken-development/",
        "",
    ),
    A(
        "Rosebank Phase 1",
        "2023",
        "TechnipFMC",
        "sps",
        "Integrated iEPCI: SPS + SURF + installation (SINGLE contract — do not triple-count)",
        "500",
        "1000",
        "band",
        "large",
        "operator",
        "World Oil",
        "https://worldoil.com/news/2023/9/28/technip-fmc-wins-large-subsea-contract-for-equinor-s-rosebank-oil-field-worth-up-to-1-billion/",
        "One iEPCI spanning sps+surf+install; recorded once under sps.",
    ),
    A(
        "Rosebank Phase 1",
        "2023",
        "Odfjell Drilling (Deepsea Atlantic)",
        "drilling_rig",
        "7 firm development wells + 4 options, integrated services",
        "328",
        "328",
        "point",
        "",
        "operator",
        "Equinor",
        "https://www.equinor.com/news/20230927-rosebank-field-to-progress-in-the-uk",
        "",
    ),
    A(
        "Rosebank Phase 1",
        "2023",
        "Aker Solutions (JV Drydocks World Dubai)",
        "production_hub",
        "EPC upgrade / life-extension of redeployed FPSO Petrojarl Knarr",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Aker Solutions",
        "https://www.akersolutions.com/news/news-archive/2023/aker-solutions-wins-rosebank-fpso-contract-from-altera-infrastructure/",
        "Aker stated NOK 2.5bn (~$0.24bn); no official USD, not counted. FPSO chartered from Altera.",
    ),
    # ===== US GoM legacy (frame-agreement regime) =====
    A(
        "Jack/St. Malo (initial phase)",
        "2010",
        "Cameron (OneSubsea)",
        "sps",
        "12 subsea trees 15k psi + manifolds + engineering/PM",
        "230",
        "230",
        "point",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/projects/jackstmalodeepwaterp/",
        "",
    ),
    A(
        "Jack/St. Malo (initial phase)",
        "2011",
        "Samsung Heavy Industries",
        "production_hub",
        "Semi FPU hull (~56,000 t, Geoje)",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Offshore Magazine",
        "https://www.offshore-mag.com/field-development/article/16758344/chevron-advances-deepwater-frontier-with-jack-st-malo-project",
        "",
    ),
    A(
        "Jack/St. Malo (initial phase)",
        "2011",
        "Technip",
        "surf",
        "EPCI >85 km flowlines/SCRs/PLETs ('major' — legacy descriptive title, pre-band)",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "TechnipFMC",
        "https://www.technipfmc.com/media/hkxoc2ov/technip-awarded-a-major-subsea-contract-for-the-jack-st-malo-fields-in-the-gulf-of-mexico-id423.pdf",
        "2011 'major' is a title, NOT the modern >$1bn band — treated as not_public.",
    ),
    A(
        "Stampede",
        "2014",
        "FMC Technologies",
        "sps",
        "15k-psi EVDT trees + manifolds (2 drill centres)",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "OEDigital",
        "https://www.oedigital.com/news/444632-slow-and-steady-wins-the-race",
        "",
    ),
    A(
        "Stampede",
        "2014",
        "Subsea 7",
        "installation",
        "Install flowlines/SCRs/umbilicals/jumpers",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/news/newssubsea-7-wins-installation-contract-for-stampede-project-us-gulf-of-mexico-4472643/",
        "",
    ),
    A(
        "Stampede",
        "2013",
        "Diamond Offshore (BlackLion + BlackRhino)",
        "drilling_rig",
        "Two-rig GoM program (~7 rig-years, NOT Stampede-only)",
        NP,
        NP,
        "combined",
        "",
        "operator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/two-diamond-drillships-for-hess/",
        "Combined ~$1.02bn backlog across both rigs and multiple projects — upper bound only, not project-attributable.",
    ),
    A(
        "Shenzi",
        "2007",
        "Technip",
        "surf",
        "EPCI infield flowlines + SCRs + PLETs (Deep Blue)",
        "75",
        "75",
        "point",
        "",
        "operator",
        "Oil & Gas Journal",
        "https://www.ogj.com/exploration-development/article/17287916/technip-to-install-flowlines-for-shenzi-field-in-gom",
        "",
    ),
    A(
        "Big Foot",
        "2011",
        "GE Oil & Gas",
        "surf",
        "Largest TLP push-up marine riser tensioner systems",
        "45",
        "45",
        "point",
        "",
        "operator",
        "Offshore Energy",
        "https://www.offshore-energy.biz/usa-ge-recieves-usd-45-million-contract-for-supply-of-tlp-tensioner-system-to-chevron/",
        "",
    ),
    A(
        "Big Foot",
        "2009",
        "Enbridge",
        "other",
        "Oil export pipeline / gathering system",
        "200",
        "200",
        "midstream",
        "",
        "operator",
        "Offshore Technology",
        "https://www.offshore-technology.com/projects/bigfootoilfield/",
        "Enbridge-owned export infra — outside Chevron's project capex.",
    ),
    A(
        "Tiber-Guadalupe",
        "2025",
        "TechnipFMC",
        "sps",
        "iEPCI Tiber 20K greenfield (SPS + SURF + install, single contract — do not triple-count)",
        "600",
        "800",
        "band",
        "large",
        "operator",
        "World Oil",
        "https://worldoil.com/news/2026/1/6/technipfmc-wins-subsea-work-for-bp-s-tiber-development-in-u-s-gulf/",
        "Disclosed $600-800m range; one iEPCI spanning sps+surf+install, recorded once.",
    ),
    A(
        "Tiber-Guadalupe",
        "2025",
        "Seatrium",
        "production_hub",
        "EPC Tiber FPU (80 kbopd, >85% design replicated from Kaskida)",
        NP,
        NP,
        "not_public",
        "",
        "operator",
        "Ocean Energy Resources",
        "https://ocean-energyresources.com/2025/11/26/seatrium-awarded-second-deepwater-fpu-contract-from-bp/",
        "",
    ),
]

# Big Foot cost-revision trail (from the GoM pass) — appended to the trails table.
TRAIL_FIELDS = [
    "PROJECT",
    "IN_SANCTIONED_SET",
    "STATEMENT_DATE",
    "VALUE_MM",
    "CURRENCY",
    "KIND",
    "BASIS",
    "PROVENANCE",
    "CONFIDENCE",
    "SOURCE_TITLE",
    "SOURCE_URL",
    "QUOTED_TEXT",
    "ACCESSED_DATE",
    "NOTES",
]
BIGFOOT_TRAIL = [
    dict(
        zip(
            TRAIL_FIELDS,
            [
                "Big Foot",
                "True",
                "2010",
                "4000",
                "USD",
                "sanction_estimate",
                "gross project cost at Dec-2010 sanction",
                "operator",
                "medium",
                "Chevron sanction (Offshore Technology profile)",
                "https://www.offshore-technology.com/projects/bigfootoilfield/",
                "'Project Cost: $4 billion'",
                D,
                "Matches the sanctioned_projects figure; the final grew after the 2015 tendon failure.",
            ],
        )
    ),
    dict(
        zip(
            TRAIL_FIELDS,
            [
                "Big Foot",
                "True",
                "2018",
                "5100",
                "USD",
                "final_outturn",
                "final gross project cost at first oil (Nov 2018), +28% vs FID",
                "trade_press",
                "low",
                "Drilling Contractor (quoting Chevron)",
                "https://drillingcontractor.org/lonestar-energy-fabrication-completes-work-on-big-foot-extended-tension-leg-platform-35084",
                "'The platform cost approximately $5.1 billion'",
                D,
                "Chevron-attributed via trade press; a direct operator restatement would upgrade the tier.",
            ],
        )
    ),
]


def _append(path, fields, new_rows, key_fields):
    with open(path, newline="", encoding="utf-8") as fh:
        existing = list(csv.DictReader(fh))
    seen = {tuple(r[k] for k in key_fields) for r in existing}
    added = 0
    with open(path, "a", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        for r in new_rows:
            if tuple(r[k] for k in key_fields) in seen:
                continue
            w.writerow(r)
            added += 1
    return added, len(existing) + added


def main() -> int:
    a_added, a_total = _append(
        CURATED / "contract_awards.csv",
        AWARD_FIELDS,
        AWARDS,
        ["PROJECT", "CONTRACTOR", "ASSET_CLASS", "AWARD_YEAR"],
    )
    t_added, t_total = _append(
        CURATED / "cost_revision_trails.csv",
        TRAIL_FIELDS,
        BIGFOOT_TRAIL,
        ["PROJECT", "STATEMENT_DATE", "KIND", "CURRENCY"],
    )
    print(f"contract_awards: +{a_added} rows (now {a_total})")
    print(f"cost_revision_trails: +{t_added} rows (now {t_total})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
