DECLARE @API_WELL_NUMBER NVARCHAR(10) = {};

--DECLARE @API_WELL_NUMBER NVARCHAR(10) = '6081240095';

SELECT API12, COMPLETION_NAME, PRODUCTION_DATE, PRODUCT_CODE, DAYS_ON_PROD, MON_O_PROD_VOL, TYPE_CODE
FROM

(SELECT API_WELL_NUMBER as API12, COMPLETION_NAME, PRODUCTION_DATE, PRODUCT_CODE, DAYS_ON_PROD, MON_O_PROD_VOL
FROM [dbo].[yearly_production_data]
WHERE LEFT(API_WELL_NUMBER,10) = @API_WELL_NUMBER
)
AS ProductionData

JOIN
(SELECT [API_WELL_NUMBER] as WELLAPI, [WELL_TYPE_CODE] as TYPE_CODE
FROM [dbo].[mv_boreholes]
)
AS BoreHoleData
on ProductionData.API12 = BoreHoleData.WELLAPI
