DECLARE @API_WELL_NUMBER NVARCHAR(10) = {};

--DECLARE @API_WELL_NUMBER NVARCHAR(10) = '6081240095';

SELECT API12, WELL_NAME, [RIG_NAME],[WAR_START_DT],[WAR_END_DT],DATEDIFF(day, WAR_START_DT, WAR_END_DT) AS [ACTIVE_DAYS], WELL_ACTIVITY_CD,[BOREHOLE_STAT_DESC],[DRILLING_MD],[DRILL_FLUID_WGT]
FROM
(SELECT [API_WELL_NUMBER] as API12
FROM [dbo].[mv_api_list]
WHERE LEFT(API_WELL_NUMBER,10) = @API_WELL_NUMBER
)
AS APIListTable

JOIN
(SELECT [SN_WAR],[API_WELL_NUMBER],[RIG_NAME], CONVERT(DATE, [WAR_START_DT]) as [WAR_START_DT], CONVERT(DATE, [WAR_END_DT]) as [WAR_END_DT], WELL_NAME
FROM [dbo].[mv_war_main]
)
AS WAR_MAIN_QUERY
on APIListTable.API12 = WAR_MAIN_QUERY.API_WELL_NUMBER

JOIN
(SELECT [SN_WAR],[WELL_ACTIVITY_CD],[DRILLING_MD],[DRILL_FLUID_WGT]
FROM [dbo].[mv_war_main_prop]
)
AS WAR_PROPERTIES
on WAR_PROPERTIES.SN_WAR = WAR_MAIN_QUERY.SN_WAR

JOIN
(SELECT [Value],[Description] as BOREHOLE_STAT_DESC
FROM [dbo].[BOREHOLE_STATUS_CDS]
)
AS BOREHOLE_STATUS_DESC
on WAR_PROPERTIES.WELL_ACTIVITY_CD = BOREHOLE_STATUS_DESC.Value

ORDER BY WELL_NAME, API12, WAR_START_DT




            SELECT API12, COMPLETION_NAME, PRODUCTION_DATE, PRODUCT_CODE, DAYS_ON_PROD, MON_O_PROD_VOL, TYPE_CODE
FROM

(SELECT API_WELL_NUMBER as API12, COMPLETION_NAME, PRODUCTION_DATE, PRODUCT_CODE, DAYS_ON_PROD, MON_O_PROD_VOL
FROM [dbo].[yearly_production_data]
WHERE LEFT(API_WELL_NUMBER,10) = @API_WELL_NUMBER
)
AS ProductionData

JOIN
(SELECT [API_WELL_NUMBER] as WELLAPI, [WELL_TYPE_CODE] as TYPE_CODE
FROM [dbo].[mv_boreholes]
)
AS BoreHoleData
on ProductionData.API12 = BoreHoleData.WELLAPI
