DECLARE @API_WELL_NUMBER NVARCHAR(10) = {};

--DECLARE @API_WELL_NUMBER NVARCHAR(10) = '6081240095';

SELECT API12, [COMP_LATITUDE],[COMP_LONGITUDE],[COMP_RSVR_NAME],[COMP_INTERVAL_NAME]
FROM
(SELECT [API_WELL_NUMBER] as API12
FROM [dbo].[mv_api_list]
WHERE LEFT(API_WELL_NUMBER,10) = @API_WELL_NUMBER
)
AS APIListTable

JOIN
(SELECT API_WELL_NUMBER, SN_EOR, WELL_NAME
FROM [dbo].[mv_eor_mainquery]
)
AS EOR_MAIN_QUERY
on APIListTable.API12 = EOR_MAIN_QUERY.API_WELL_NUMBER

JOIN
(SELECT [SN_EOR_FK],[SN_EOR_WELL_COMP],[COMP_LATITUDE],[COMP_LONGITUDE],[COMP_RSVR_NAME],[COMP_INTERVAL_NAME]
FROM [dbo].[mv_eor_completionsprop]
)
AS EOR_COMPLETIONSPROP_QUERY
on EOR_MAIN_QUERY.SN_EOR = EOR_COMPLETIONSPROP_QUERY.SN_EOR_FK
