DECLARE @API_WELL_NUMBER NVARCHAR(10) = {};

--DECLARE @API_WELL_NUMBER NVARCHAR(10) = '6081240095';

SELECT API12,[INCL_ANG_DEG_VAL] ,[INCL_ANG_MIN_VAL],[SURVEY_POINT_MD],[WELL_N_S_CODE],[DIR_DEG_VAL],[DIR_MINS_VAL],[WELL_E_W_CODE],[SURVEY_POINT_TVD],[DELTA_X],[DELTA_Y],[SURF_LONGITUDE],[SURF_LATITUDE]
FROM
(SELECT [API_WELL_NUMBER] as API12
FROM [dbo].[mv_api_list]
WHERE LEFT(API_WELL_NUMBER,10) = @API_WELL_NUMBER
)
AS APIListTable

JOIN
(SELECT [API_WELL_NUMBER],[INCL_ANG_DEG_VAL] ,[INCL_ANG_MIN_VAL],[SURVEY_POINT_MD],[WELL_N_S_CODE],[DIR_DEG_VAL],[DIR_MINS_VAL],[WELL_E_W_CODE],[SURVEY_POINT_TVD],[DELTA_X],[DELTA_Y],[SURF_LONGITUDE],[SURF_LATITUDE]
FROM [dbo].[directionalsurveys]
)
AS DIRECTIONAL_SURVEY_QUERY
on APIListTable.API12 = DIRECTIONAL_SURVEY_QUERY.API_WELL_NUMBER
ORDER BY API12, SURVEY_POINT_MD
