DECLARE @API_WELL_NUMBER NVARCHAR(10) = {};

--DECLARE @API_WELL_NUMBER NVARCHAR(10) = '6081240095';

SELECT API12, WELL_NAME, [WAR_START_DT], [WAR_END_DT], [CSNG_INTV_TYPE_CD],[CSNG_HOLE_SIZE],[CSNG_SETTING_BOTM_MD],[CSNG_SETTING_TOP_MD],[CASING_SIZE],[CASING_WEIGHT],[CASING_GRADE],[CSNG_LINER_TEST_PRSS],[CSNG_SHOE_TEST_PRSS],[CSNG_CEMENT_VOL],[SN_WAR_CSNG_INTV]
FROM
(SELECT [API_WELL_NUMBER] as API12
FROM [dbo].[mv_api_list]
WHERE LEFT(API_WELL_NUMBER,10) = @API_WELL_NUMBER
)
AS APIListTable

JOIN
(SELECT [SN_WAR],[API_WELL_NUMBER], [WAR_START_DT], [WAR_END_DT], WELL_NAME
FROM [dbo].[mv_war_main]
)
AS WAR_MAIN_QUERY
on APIListTable.API12 = WAR_MAIN_QUERY.API_WELL_NUMBER

JOIN
(SELECT [SN_WAR_FK], [CSNG_INTV_TYPE_CD],[CSNG_HOLE_SIZE],[CASING_SIZE],[CASING_WEIGHT],[CASING_GRADE]
,[CSNG_LINER_TEST_PRSS],[CSNG_SHOE_TEST_PRSS],[CSNG_CEMENT_VOL],[SN_WAR_CSNG_INTV]
FROM [dbo].[mv_war_tubular_summaries]
)
AS WAR_tubular_summaries_QUERY
on WAR_MAIN_QUERY.SN_WAR= WAR_tubular_summaries_QUERY.SN_WAR_FK

JOIN
(SELECT [SN_WAR_CSNG_INTV_FK],[SN_WAR_FK],[CSNG_SETTING_BOTM_MD],[CSNG_SETTING_TOP_MD]
FROM [dbo].[mv_war_tubular_summaries_prop]
)
AS WAR_war_tubular_summaries_prop_QUERY
on WAR_tubular_summaries_QUERY.SN_WAR_CSNG_INTV = WAR_war_tubular_summaries_prop_QUERY.SN_WAR_CSNG_INTV_FK
