"""Render the subsea-manifold supplier market-intelligence report.

Reads the curated database through :class:`ManifoldSupplierLoader` (no
hand-keyed numbers) and writes a Markdown report to
``reports/subsea/subsea_manifold_market_intelligence.md``.

Usage:
    uv run python scripts/generate_manifold_market_report.py
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from worldenergydata.subsea import ManifoldSupplierLoader

TIER_LABELS = {
    "tier_1": "Tier 1 — integrated SPS OEM / major EPCI",
    "tier_2": "Tier 2 — established specialist OEM",
    "niche": "Niche — independent custom hardware",
    "adjacency": "Adjacency — enabling subsystems, not a manifold OEM",
}
ROLE_LABELS = {
    "OEM": "Manifold OEM",
    "EPC": "EPC / EPCI / SURF",
    "fabricator": "Structural fabricator / integrator",
    "subsystem_supplier": "Subsystem supplier (power / controls)",
    "limited": "Limited / not a direct manifold supplier",
}


def render() -> str:
    loader = ManifoldSupplierLoader()
    recs = loader.all()
    collection_date = recs[0].COLLECTION_DATE if recs else "unknown"

    lines: list[str] = []
    lines.append("# Subsea Manifolds — Key Players Market Intelligence")
    lines.append("")
    lines.append(
        f"_Source: `worldenergydata` curated DB "
        f"(`data/modules/subsea/curated/manifold_suppliers.csv`), "
        f"{len(recs)} suppliers, collected {collection_date}. "
        f"Generated by `scripts/generate_manifold_market_report.py` — "
        f"do not hand-edit numbers._"
    )
    lines.append("")

    # --- Snapshot counts ---
    roles = Counter(r.MANIFOLD_ROLE for r in recs)
    tiers = Counter(r.ROLE_TIER for r in recs)
    lines.append("## Market structure at a glance")
    lines.append("")
    lines.append("| Competitive tier | Count | Companies |")
    lines.append("|---|---|---|")
    for tier_key, label in TIER_LABELS.items():
        members = [r.COMPANY for r in recs if r.ROLE_TIER == tier_key]
        if members:
            lines.append(
                f"| {label} | {tiers[tier_key]} | {', '.join(members)} |"
            )
    lines.append("")
    lines.append("| Role in manifold supply | Count |")
    lines.append("|---|---|")
    for role_key, label in ROLE_LABELS.items():
        if roles.get(role_key):
            lines.append(f"| {label} | {roles[role_key]} |")
    lines.append("")

    # --- Capability table ---
    lines.append("## Supplier capability matrix")
    lines.append("")
    lines.append(
        "| Company | Ticker | HQ | Role | Tier | Max WD (m) | Parent / JV |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    for r in sorted(
        recs,
        key=lambda x: (x.MAX_WATER_DEPTH_M or 0),
        reverse=True,
    ):
        wd = r.MAX_WATER_DEPTH_M if r.MAX_WATER_DEPTH_M is not None else "—"
        lines.append(
            f"| {r.COMPANY} | {r.TICKER or '—'} | {r.HQ_COUNTRY or '—'} | "
            f"{r.MANIFOLD_ROLE or '—'} | {r.ROLE_TIER or '—'} | {wd} | "
            f"{r.PARENT_OR_JV or '—'} |"
        )
    lines.append("")

    # --- Key finding ---
    lines.append("## Key findings")
    lines.append("")
    lines.append(
        "- **Consolidation around three SPS majors.** The integrated subsea "
        "production system (manifolds + trees + controls) market is "
        "dominated by **TechnipFMC**, **SLB OneSubsea** (the SLB 70% / Aker "
        "Solutions 20% / Subsea7 10% JV, closed Oct 2023), and **Baker "
        "Hughes**. Aker Solutions and Subsea7 now reach the manifold-OEM "
        "market primarily *through* the OneSubsea JV."
    )
    lines.append(
        "- **EPCI vs OEM split.** **McDermott** and **Subsea7** are tier-1 "
        "EPCI/SURF players that fabricate and install manifolds but integrate "
        "third-party SPS hardware rather than manufacturing the valve/control "
        "internals."
    )
    lines.append(
        "- **Independents fill custom / fast-track demand.** **Trendsetter "
        "Engineering** (niche, private) and **Dril-Quip/Innovex** (tier-2) "
        "supply fit-for-purpose manifolds and connection systems; Trendsetter "
        "acquired Innovex's subsea-tree line in 2025."
    )
    lines.append(
        "- **Adjacencies, not manifold OEMs.** **ABB** (subsea power & "
        "automation) and **Halliburton** (subsea completions & intervention) "
        "appear in some 'subsea manifold market' lists but do **not** "
        "manufacture manifolds — they supply enabling subsystems."
    )
    lines.append(
        "- **Live M&A to watch.** The **Saipem–Subsea7 merger ('Saipem7')** "
        "was signed in July 2025 and remains pending regulatory clearance "
        "(UK CMA) as of June 2026."
    )
    lines.append("")

    # --- Per-company detail ---
    lines.append("## Company profiles")
    lines.append("")
    for r in recs:
        lines.append(f"### {r.COMPANY}")
        lines.append("")
        lines.append(
            f"- **Ticker:** {r.TICKER or '—'} · **HQ:** "
            f"{r.HQ_CITY or '—'}, {r.HQ_COUNTRY or '—'}"
        )
        lines.append(
            f"- **Role / tier:** {r.MANIFOLD_ROLE or '—'} / "
            f"{r.ROLE_TIER or '—'} · **Max water depth:** "
            f"{r.MAX_WATER_DEPTH_M or '—'} m"
        )
        if r.PARENT_OR_JV:
            lines.append(f"- **Parent / JV:** {r.PARENT_OR_JV}")
        lines.append(f"- **Position:** {r.MARKET_POSITION or '—'}")
        if r.PRODUCT_LINES:
            lines.append(
                "- **Manifold-relevant product lines:** "
                + "; ".join(r.PRODUCT_LINES)
            )
        if r.NOTABLE_PROJECTS:
            lines.append(
                "- **Notable projects:** " + "; ".join(r.NOTABLE_PROJECTS)
            )
        if r.RECENT_DEVELOPMENTS:
            lines.append(
                "- **Recent (2024-2026):** "
                + "; ".join(r.RECENT_DEVELOPMENTS)
            )
        if r.NOTES:
            lines.append(f"- **Notes:** {r.NOTES}")
        if r.DATA_SOURCE_URLS:
            srcs = " · ".join(f"<{u}>" for u in r.DATA_SOURCE_URLS)
            lines.append(f"- **Sources:** {srcs}")
        lines.append("")

    return "\n".join(lines)


def main() -> Path:
    out = (
        Path(__file__).resolve().parents[1]
        / "reports"
        / "subsea"
        / "subsea_manifold_market_intelligence.md"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(), encoding="utf-8")
    print(f"Wrote report: {out}")
    return out


if __name__ == "__main__":
    main()
