@startuml package_development
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title BSEE Data

start

    partition "New Library - Setup" {


        :Download API data;
            note right
                - Use local/supabase data
                - user well if not found -> download
            end note

        :Get other data;
            note right
                yml file data
                - Production data  
                Initilize this as new repo using choice tools i.e. IDE, Host etc.
            end note

    }

    partition "Development" {
    :Write test;
        note right
            For Test Driven Development (TDD)
            Modify template test
        end note
    :Install Package locally i.e.
    an editable install;
        note right
            Use .toml file //python -m pip install -e .//
            (or)
            Use conda-build //conda develop .//
            Development in an IDE with breakpoints 
            on local files etc.
        end note
    }



stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml