@startuml bsee_data_api
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title BSEE Data API Selenium Workflow

start

            note right
              All manual operations performed by Selenium
            end note

    partition {


        :Open Browser | manual;
            note right
                - Selenium
            end note

        :Enter WellAPI12 and submit query | manual;
            note right
                - URL does not change
                - Grid appears
                - Explore: Does grid have a sub url we can use?
            end note

        : Download CSV;
            note right
            TBA
            end note

        :Read all CSVs;
            note right
            TBA
            end note


    }

stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml