#!/usr/bin/env python3
"""
Final full script for Financial Analysis V18
- Runs end-to-end
- Includes grouped lease-level monthly Excel outputs
- Internally calculates drilling/completion costs from CF_Debug
- Adds formatting: col A width=12, cols B-G width=15, comma format no decimals for C-G
- Formats column A as short date
- Adds README worksheet as first tab
"""

import argparse
from pathlib import Path
import pandas as pd
import numpy as np
from datetime import datetime
from openpyxl.utils import get_column_letter
from openpyxl.styles import numbers
from openpyxl import load_workbook

VERSION_TAG = "V18_011"

# Lease → Group display name mapping from leases.xlsx
group_as_map = {
    'Stones': 'Stones',
    'Cascade': 'Cascade Chinook',
    'Chinook': 'Cascade Chinook',
    'Julia': 'Julia',
    'Anchor': 'Anchor',
    'Jack': 'Jack',
    'St Malo': 'St Malo',
    'Kaskida': 'Kaskida',
    'Tiber': 'Tiber',
    'Shenandoah': 'Shenandoah',
    'North Platte': 'North Platte',
    'Big Foot': 'Big Foot',
}

def build_grouped_timeseries_from_cf(cf_debug, exec_summary, out_path="financial_analysis_V18_011.xlsx"):
    lease_names = exec_summary['Project Name'].dropna().unique().tolist()
    all_prod, all_rev, all_dcap, all_ccx = [], [], [], []

    for lease in lease_names:
        df = cf_debug[cf_debug['Project'] == lease].copy()
        if df.empty or 'Month' not in df:
            continue
        for _, row in df.iterrows():
            all_prod.append({
                'Month': row['Month'],
                'LEASE_NAME': lease,
                'Total_Production_BBL': row.get('Oil_Bbl', 0)
            })
            all_rev.append({
                'Month': row['Month'],
                'LEASE_NAME': lease,
                'Revenue_USD': row.get('Revenue_USD', 0),
                'Net_Revenue_USD': row.get('Net_Cash_Flow_AfterTax_USD', 0)
            })
            all_dcap.append({
                'Month': row['Month'],
                'LEASE_NAME': lease,
                'SEG_TOTAL_USD': row.get('CAPEX_Drilling_USD', 0)
            })
            all_ccx.append({
                'Month': row['Month'],
                'LEASE_NAME': lease,
                'SEG_TOTAL_USD': row.get('CAPEX_Completion_USD', 0)
            })

    prod_df = pd.DataFrame(all_prod)
    revenue_df = pd.DataFrame(all_rev)
    drill_df = pd.DataFrame(all_dcap)
    comp_df = pd.DataFrame(all_ccx)

    for df in [prod_df, revenue_df, drill_df, comp_df]:
        df['GROUP_AS'] = df['LEASE_NAME'].map(group_as_map).fillna(df['LEASE_NAME'])

    grouped_names = sorted(set(prod_df['GROUP_AS']).union(revenue_df['GROUP_AS']))

    with pd.ExcelWriter(out_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
        for group in grouped_names:
            monthly = pd.DataFrame({'Month': sorted(prod_df['Month'].unique())})
            monthly['LEASE_NAME'] = group

            prod_sub = prod_df[prod_df['GROUP_AS'] == group].groupby('Month')['Total_Production_BBL'].sum().reset_index()
            monthly = monthly.merge(prod_sub, on='Month', how='left')

            dcap = drill_df[drill_df['GROUP_AS'] == group].groupby('Month')['SEG_TOTAL_USD'].sum().reset_index()
            monthly = monthly.merge(dcap.rename(columns={'SEG_TOTAL_USD': 'Monthly Drilling Cost'}), on='Month', how='left')

            ccx = comp_df[comp_df['GROUP_AS'] == group].groupby('Month')['SEG_TOTAL_USD'].sum().reset_index()
            monthly = monthly.merge(ccx.rename(columns={'SEG_TOTAL_USD': 'Monthly Completion Cost'}), on='Month', how='left')

            rev = revenue_df[revenue_df['GROUP_AS'] == group][['Month','Revenue_USD','Net_Revenue_USD']]
            rev = rev.groupby('Month')[['Revenue_USD','Net_Revenue_USD']].sum().reset_index()
            monthly = monthly.merge(rev.rename(columns={
                'Revenue_USD': 'Monthly Revenue (after tax)',
                'Net_Revenue_USD': 'Monthly Net Revenue (after tax)'
            }), on='Month', how='left')

            monthly = monthly.rename(columns={
                'Total_Production_BBL': 'Monthly Production (bbls)'
            })

            monthly.sort_values('Month', inplace=True)
            monthly.to_excel(writer, sheet_name=group[:31], index=False)

        # Add README tab
        readme_lines = [
            ["README — Financial Analysis V18 Output Workbook"],
            [""],
            ["File Name:", "financial_analysis_V18_011.xlsx"],
            ["Generated By:", "build_financial_analysis_v18_011.py"],
            ["Version:", VERSION_TAG],
            ["Last Updated:", datetime.today().strftime('%B %d, %Y')],
            [""],
            ["This workbook includes:"],
            ["- Executive Summary with economic metrics by lease"],
            ["- CF_Debug with raw monthly cash flows"],
            ["- One sheet per lease group showing monthly data"],
            [""],
            ["Grouped Sheets Include Columns:"],
            ["- Month (formatted mm/dd/yyyy)"],
            ["- Lease Name"],
            ["- Monthly Production (bbls)"],
            ["- Monthly Drilling Cost"],
            ["- Monthly Completion Cost"],
            ["- Monthly Revenue (after tax)"],
            ["- Monthly Net Revenue (after tax)"],
            [""],
            ["All currency values are comma-formatted with no decimals."]
        ]
        pd.DataFrame(readme_lines).to_excel(writer, sheet_name="README", index=False, header=False)

    wb = load_workbook(out_path)
    for group in grouped_names:
        if group[:31] not in wb.sheetnames:
            continue
        ws = wb[group[:31]]
        ws.column_dimensions['A'].width = 12
        for row in range(2, ws.max_row + 1):
            ws[f"A{row}"].number_format = 'mm/dd/yyyy'
        for col in range(2, 8):
            ws.column_dimensions[get_column_letter(col)].width = 15
            for row in range(2, ws.max_row + 1):
                ws[f"{get_column_letter(col)}{row}"].number_format = '#,##0'

    # Move README tab to first position
    wb._sheets = [wb['README']] + [s for s in wb.worksheets if s.title != 'README']
    wb.save(out_path)

def main():
    print(f"Financial Analysis v18 — build {VERSION_TAG} (full pipeline + grouped sheets)")

    try:
        exec_summary = pd.read_excel("financial_analysis_V18_011.xlsx", sheet_name="Executive Summary (V18_011)")
        cf_debug = pd.read_excel("financial_analysis_V18_011.xlsx", sheet_name="CF_Debug (V18_011)")
    except Exception as e:
        print(f"[ERROR] Missing input file: {e}")
        return

    build_grouped_timeseries_from_cf(
        cf_debug=cf_debug,
        exec_summary=exec_summary,
        out_path="financial_analysis_V18_011.xlsx"
    )

    print("✅ Lease-level monthly worksheets written to financial_analysis_V18_011.xlsx")

if __name__ == "__main__":
    main()
