@startuml high_level_architecture
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title High Level Architecture

start

    partition {

        :Data;
            note right
                Well 
                Production 
                block
            end note

        :Analysis;
            note right
                well basic - single API 
                Production data
                block 
            end note

        
    }

stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml++
